include::ROOT:partial$attributes.adoc[]

= Resource policies

[source,yaml,linenums]
----
---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default" <1>
  importDerivedRoles:
    - apatr_common_roles <2>
  resource: "album:object"  <3>
  rules:
    - actions: ['*'] <4>
      effect: EFFECT_ALLOW
      derivedRoles:
        - owner <5>

    - actions: ['view']
      effect: EFFECT_ALLOW
      roles:
        - user <6>
      condition:
        match:
          expr: request.resource.attr.public == true

    - name: moderator_rule <7>
      actions: ['view', 'delete']
      effect: EFFECT_ALLOW
      derivedRoles:
        - abuse_moderator
----
<1> Version of this policy. Policies are uniquely identified by the resource name and version pair. You can have multiple policy versions for the same resource (e.g. production vs. staging). The version value `default` is special as it is the default fallback when no version is specified in the request.
<2> Import a set of derived roles.
<3> Name of the resource to which this policy applies.
<4> Actions can contain wildcards. Wildcards honour the ``:`` delimiter. E.g. ``a:*:d`` would match ``a:x:d`` but not ``a:x``.
<5> This rule applies to a derived role.
<6> Rules can also refer directly to static roles.
<7> Optional name for the rule.

== Another example
[source,yaml,linenums]
----
---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  importDerivedRoles:
  - my_derived_roles
  resource: leave_request
  globals: <1>
    pending_approval: ("PENDING_APPROVAL")
    principal_location: |-
      (P.attr.ip_address.inIPAddrRange("10.20.0.0/16") ? "GB" : "")
  rules:
  - actions: ["approve"]
    condition:
      match:
        expr: request.resource.attr.status == globals.pending_approval
    derivedRoles:
      - direct_manager
    effect: EFFECT_ALLOW
  - actions: ["delete"]
    condition:
      match:
        expr: request.resource.attr.geography == globals.principal_location
    derivedRoles:
    - direct_manager
    effect: EFFECT_ALLOW
----
<1> This resource policy includes global variables section. Each variable is evaluated before evaluating any rule condition.
A variable expression can contain anything that condition expression can have.