include::ROOT:partial$attributes.adoc[]

= Role policies

include::ROOT:partial$version-check.adoc[]

Role policies are ABAC policies in which you specify a number of resources, each with a set of allowable actions that the role can carry out on the resource. Optionally, a condition can also be specified for each set of allowable actions. In the simple case, they allow you to author permissions from the view of an IdP role, rather than for a given resource.

Role policies are not standalone. They apply as an additive constraint on top of xref:resource_policies.adoc[resource policies], so an action is only allowed if it is permitted by both the role policy and a matching resource policy. A role policy cannot grant access that the resource policy does not already allow, which means a resource policy is always required.

Unlike resource and principal policies, role policies do not define explicit `ALLOW` or `DENY` effects. Instead, the **allowable actions** act as an exhaustive list of actions allowed on each resource. Any resource and action pair not defined in this list is immediately denied for that role.

The name of a role policy is effectively a custom role within the context of Cerbos. A role policy (custom role) can optionally define `parentRoles`, inheriting and narrowing their permissions by default. The policy can only define rules that are a strict subset of the parent role’s permissions and cannot introduce any extra rules beyond what the parent roles allow. They can immediately DENY an action but if they ALLOW an action, a parent policy higher up the scope chain must also ALLOW the same action.

A parent role can be either an arbitrary IdP role or the name of another role policy within the system. Parent role resolution is recursive—if a custom role inherits from another custom role that also has parent roles, it inherits and narrows their permissions as well.

[source,yaml,linenums]
----
---
apiVersion: api.cerbos.dev/v1
rolePolicy:
  role: "acme_admin" <1>
  version: "default" <2>
  scope: "acme.hr.uk" <3>
  parentRoles: <4>
    - admin
  constants:
    import: <5>
      - apatr_common_constants
    local: <6>
      corporate_network_ip_range: 10.20.0.0/16
  variables:
    import: <7>
      - apatr_common_variables
    local: <8>
      is_corporate_network: |-
        P.attr.ip_address.inIPAddrRange(constants.corporate_network_ip_range)
  rules:
    - resource: leave_request <9>
      allowActions: <10>
        - view:* <11>
        - deny

    - resource: salary_record
      name: salary_record_owner <12>
      allowActions:
        - edit
      condition: <13>
        match:
          expr: R.attr.owner == P.id && variables.is_corporate_network
      output: <14>
        when:
          ruleActivated: |-
            "salary_record_edited:%s".format([P.id])
          conditionNotMet: |-
            "salary_record_edit_blocked:%s".format([P.id])

    - resource: "*" <15>
      allowActions: ["create"]
----
<1> The role to which this policy applies.
<2> Version of this policy. Policies are uniquely identified by the role name and version pair. You can have multiple policy versions for the same role (e.g. production vs. staging). The version value `default` is special as it is the default fallback when no version is specified in the request.
<3> Optional principal xref:scoped_policies.adoc[scope] for this policy.
<4> The list of parent roles that the custom role inherits.
<5> xref:variables.adoc#export-constants[Constant definitions] to import (optional).
<6> xref:variables.adoc#local-constants[Local constant definitions] (optional).
<7> xref:variables.adoc#export[Variable definitions] to import (optional).
<8> xref:variables.adoc#local[Local variable definitions] (optional).
<9> The resource to which the following rule applies.
<10> The list of allowable actions that the role can carry out on the given resource.
<11> Wildcard actions are supported.
<12> Optional name for the rule.
<13> A condition that must be met for the action to be allowed.
<14> Optional output for the action rule. You can define optional expressions to be evaluated as output depending on whether the rule is activated or not activated because of a condition failure.
<15> Wildcard resources are also supported.
