// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cerbos/engine/v1/engine.proto

package enginev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	effectv1 "github.com/cerbos/cerbos/api/genpb/cerbos/effect/v1"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}

	_ = effectv1.Effect(0)
)

// Validate checks the field values on CheckInput with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *CheckInput) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for RequestId

	if m.GetResource() == nil {
		return CheckInputValidationError{
			field:  "Resource",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetResource()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CheckInputValidationError{
				field:  "Resource",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetPrincipal() == nil {
		return CheckInputValidationError{
			field:  "Principal",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetPrincipal()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CheckInputValidationError{
				field:  "Principal",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	_CheckInput_Actions_Unique := make(map[string]struct{}, len(m.GetActions()))

	for idx, item := range m.GetActions() {
		_, _ = idx, item

		if _, exists := _CheckInput_Actions_Unique[item]; exists {
			return CheckInputValidationError{
				field:  fmt.Sprintf("Actions[%v]", idx),
				reason: "repeated value must contain unique items",
			}
		} else {
			_CheckInput_Actions_Unique[item] = struct{}{}
		}

		if utf8.RuneCountInString(item) < 1 {
			return CheckInputValidationError{
				field:  fmt.Sprintf("Actions[%v]", idx),
				reason: "value length must be at least 1 runes",
			}
		}

	}

	if v, ok := interface{}(m.GetAuxData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CheckInputValidationError{
				field:  "AuxData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// CheckInputValidationError is the validation error returned by
// CheckInput.Validate if the designated constraints aren't met.
type CheckInputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckInputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckInputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckInputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckInputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckInputValidationError) ErrorName() string { return "CheckInputValidationError" }

// Error satisfies the builtin error interface
func (e CheckInputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckInput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckInputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckInputValidationError{}

// Validate checks the field values on CheckOutput with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CheckOutput) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for RequestId

	// no validation rules for ResourceId

	for key, val := range m.GetActions() {
		_ = val

		// no validation rules for Actions[key]

		if v, ok := interface{}(val).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CheckOutputValidationError{
					field:  fmt.Sprintf("Actions[%v]", key),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// CheckOutputValidationError is the validation error returned by
// CheckOutput.Validate if the designated constraints aren't met.
type CheckOutputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckOutputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckOutputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckOutputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckOutputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckOutputValidationError) ErrorName() string { return "CheckOutputValidationError" }

// Error satisfies the builtin error interface
func (e CheckOutputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckOutput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckOutputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckOutputValidationError{}

// Validate checks the field values on Resource with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Resource) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetKind()) < 1 {
		return ResourceValidationError{
			field:  "Kind",
			reason: "value length must be at least 1 runes",
		}
	}

	if !_Resource_Kind_Pattern.MatchString(m.GetKind()) {
		return ResourceValidationError{
			field:  "Kind",
			reason: "value does not match regex pattern \"^[[:alpha:]][[:word:]\\\\@\\\\.\\\\-/]*(\\\\:[[:alpha:]][[:word:]\\\\@\\\\.\\\\-/]*)*$\"",
		}
	}

	if !_Resource_PolicyVersion_Pattern.MatchString(m.GetPolicyVersion()) {
		return ResourceValidationError{
			field:  "PolicyVersion",
			reason: "value does not match regex pattern \"^[[:word:]]*$\"",
		}
	}

	if utf8.RuneCountInString(m.GetId()) < 1 {
		return ResourceValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
	}

	for key, val := range m.GetAttr() {
		_ = val

		if val == nil {
			return ResourceValidationError{
				field:  fmt.Sprintf("Attr[%v]", key),
				reason: "value cannot be sparse, all pairs must be non-nil",
			}
		}

		// no validation rules for Attr[key]

		if v, ok := interface{}(val).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResourceValidationError{
					field:  fmt.Sprintf("Attr[%v]", key),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ResourceValidationError is the validation error returned by
// Resource.Validate if the designated constraints aren't met.
type ResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceValidationError) ErrorName() string { return "ResourceValidationError" }

// Error satisfies the builtin error interface
func (e ResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceValidationError{}

var _Resource_Kind_Pattern = regexp.MustCompile("^[[:alpha:]][[:word:]\\@\\.\\-/]*(\\:[[:alpha:]][[:word:]\\@\\.\\-/]*)*$")

var _Resource_PolicyVersion_Pattern = regexp.MustCompile("^[[:word:]]*$")

// Validate checks the field values on Principal with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Principal) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetId()) < 1 {
		return PrincipalValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
	}

	if !_Principal_PolicyVersion_Pattern.MatchString(m.GetPolicyVersion()) {
		return PrincipalValidationError{
			field:  "PolicyVersion",
			reason: "value does not match regex pattern \"^[[:word:]]*$\"",
		}
	}

	if l := len(m.GetRoles()); l < 1 || l > 20 {
		return PrincipalValidationError{
			field:  "Roles",
			reason: "value must contain between 1 and 20 items, inclusive",
		}
	}

	_Principal_Roles_Unique := make(map[string]struct{}, len(m.GetRoles()))

	for idx, item := range m.GetRoles() {
		_, _ = idx, item

		if _, exists := _Principal_Roles_Unique[item]; exists {
			return PrincipalValidationError{
				field:  fmt.Sprintf("Roles[%v]", idx),
				reason: "repeated value must contain unique items",
			}
		} else {
			_Principal_Roles_Unique[item] = struct{}{}
		}

		if !_Principal_Roles_Pattern.MatchString(item) {
			return PrincipalValidationError{
				field:  fmt.Sprintf("Roles[%v]", idx),
				reason: "value does not match regex pattern \"^[[:word:]\\\\-\\\\.]+$\"",
			}
		}

	}

	for key, val := range m.GetAttr() {
		_ = val

		if val == nil {
			return PrincipalValidationError{
				field:  fmt.Sprintf("Attr[%v]", key),
				reason: "value cannot be sparse, all pairs must be non-nil",
			}
		}

		// no validation rules for Attr[key]

		if v, ok := interface{}(val).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PrincipalValidationError{
					field:  fmt.Sprintf("Attr[%v]", key),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// PrincipalValidationError is the validation error returned by
// Principal.Validate if the designated constraints aren't met.
type PrincipalValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PrincipalValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PrincipalValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PrincipalValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PrincipalValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PrincipalValidationError) ErrorName() string { return "PrincipalValidationError" }

// Error satisfies the builtin error interface
func (e PrincipalValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPrincipal.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PrincipalValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PrincipalValidationError{}

var _Principal_PolicyVersion_Pattern = regexp.MustCompile("^[[:word:]]*$")

var _Principal_Roles_Pattern = regexp.MustCompile("^[[:word:]\\-\\.]+$")

// Validate checks the field values on AuxData with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *AuxData) Validate() error {
	if m == nil {
		return nil
	}

	for key, val := range m.GetJwt() {
		_ = val

		// no validation rules for Jwt[key]

		if v, ok := interface{}(val).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AuxDataValidationError{
					field:  fmt.Sprintf("Jwt[%v]", key),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// AuxDataValidationError is the validation error returned by AuxData.Validate
// if the designated constraints aren't met.
type AuxDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuxDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuxDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuxDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuxDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuxDataValidationError) ErrorName() string { return "AuxDataValidationError" }

// Error satisfies the builtin error interface
func (e AuxDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuxData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuxDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuxDataValidationError{}

// Validate checks the field values on CheckOutput_ActionEffect with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CheckOutput_ActionEffect) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Effect

	// no validation rules for Policy

	return nil
}

// CheckOutput_ActionEffectValidationError is the validation error returned by
// CheckOutput_ActionEffect.Validate if the designated constraints aren't met.
type CheckOutput_ActionEffectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckOutput_ActionEffectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckOutput_ActionEffectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckOutput_ActionEffectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckOutput_ActionEffectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckOutput_ActionEffectValidationError) ErrorName() string {
	return "CheckOutput_ActionEffectValidationError"
}

// Error satisfies the builtin error interface
func (e CheckOutput_ActionEffectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckOutput_ActionEffect.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckOutput_ActionEffectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckOutput_ActionEffectValidationError{}
