---
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "api"
  - "deploy"
  - "docs"
  - "e2e"
  - "hack"
  - "tools"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
