include::ROOT:partial$attributes.adoc[]

= Engine block

== Default policy version

xref:policies:index.adoc[Cerbos policies] have a `version` field to support use cases such as having different policies for different environments (production, staging etc.) or for gradual rollout of a new version of an application. By default, when a request does not explicitly specify the policy version, the Cerbos engine attempts to find a matching policy that has its version set to `default`. You can change this fallback value by setting the `defaultPolicyVersion`. For example, if you have a Cerbos deployment for your staging environment, you may want to set `defaultPolicyVersion: staging` to ensure that the default policies in effect are the ones versioned as `staging`.


[source,yaml,linenums]
----
engine:
  defaultPolicyVersion: "default"
----

[#globals]
== Globals

Global variables are a way to pass environment-specific information to xref:policies:conditions.adoc[policy conditions]. For example, you might want to grant additional permissions to a role in your staging environment, without creating separate policy versions for different environments.

[source,yaml,linenums]
----
engine:
  globals:
    environment: "staging"
----

Values set in `globals` can then be referenced in policy conditions:

[source,yaml,linenums]
----
rules:
  - actions:
      - view
    effect: EFFECT_ALLOW
    roles:
      - developer
    condition:
      match:
        expr: globals.environment != "production"
----

As with other configuration settings, environment variables can be used to set global values.

[source,yaml,linenums]
----
engine:
  globals:
    environment: ${CERBOS_ENVIRONMENT:development}
----
