include::ROOT:partial$attributes.adoc[]

[[configuration]]
= Configuration

The Cerbos server is configured with a YAML file. Start the server by passing the configuration file using the `--config` flag. The values defined in the file can be overridden from the command-line by using the `--set` flag. The `--set` flag can be used multiple times. For example, to override `server.httpListenAddr` and `engine.defaultPolicyVersion`, the `--set` flag can be used as follows:

[source,sh,subs="attributes"]
----
./{app-name} server --config=/path/to/config.yaml --set=server.httpListenAddr=:3592 --set=engine.defaultPolicyVersion=staging
----

NOTE: Config values can reference environment variables by enclosing them between `${}`. E.g. `$$${HOME}$$`.


[source,sh,subs="attributes"]
----
./{app-name} server --config=/path/to/config.yaml --set=server.httpListenAddr=:3592 --set=engine.defaultPolicyVersion=staging
----


== Minimal Configuration
At a minimum, Cerbos requires a storage driver to be configured in order to start. You must provide a configuration file when starting the Cerbos binary. The Cerbos container ships with a default configuration that has a `disk` driver configured to  look for policies mounted at `/policies`.
.Default configuration file shipped in the container
[source,yaml,linenums]
----
---
server:
  httpListenAddr: ":3592"
  grpcListenAddr: ":3593"

storage:
  driver: "disk"
  disk:
    directory: /policies 
    watchForChanges: true
----


== Full Configuration
Cerbos has many configuration options that are either optional or has reasonable defaults built-in. The following section describes all user-configurable options and their defaults.

.Cerbos configuration file
[source,yaml,linenums]
----
---
include::partial$fullconfiguration.adoc[]
----
