include::ROOT:partial$attributes.adoc[]

= Telemetry

include::ROOT:partial$version-check.adoc[]

:page-aliases: ROOT:telemetry.adoc

Cerbos developers rely on anonymous usage data to help prioritise new features and improve the product. The information collected is completely anonymous, never shared with external entities, and you can opt out at any time.


== What kind of data is collected?

- Cerbos build information like version, commit and build date
- Operating system type and architecture
- Enabled Cerbos features (storage backend type and schema enforcement level are some examples of this information)
- Aggregated statistics about the policies like the total number of policies and average number of rules in a policy
- Aggregated statistics about Cerbos API calls and the gRPC user agents.

You can view the full schema of the telemetry data on link:https://github.com/cerbos/cerbos/tree/main/api/public/cerbos/telemetry/v1/telemetry.proto[GitHub] or on the link:https://buf.build/cerbos/cerbos-api/docs/main/cerbos.telemetry.v1[Buf schema registry].

We use link:https://www.rudderstack.com[Rudderstack] to collect the data. Only a small number of Zenauth (the company leading the development of Cerbos) employees have access to the data.

== How to disable telemetry collection

There are multiple ways in which you can disable telemetry collection.

=== Use the configuration file

Set `telemetry.disabled: true` in the xref:configuration:index.adoc[Cerbos configuration file].

[source,yaml]
----
telemetry:
  disabled: true
----

=== Set an environment variable

Set `CERBOS_NO_TELEMETRY=1` or `CERBOS_NO_TELEMETRY=true` in your environment. We also honour the `DO_NOT_TRACK` environment variable if it exists.

.With the binary
[source,sh,subs="attributes"]
----
CERBOS_NO_TELEMETRY=1 ./{app-name} server --config=/path/to/.cerbos.yaml
----

.With the container
[source,sh,subs="attributes"]
----
docker run -i -t -p 3592:3592 \
    -e CERBOS_NO_TELEMETRY=true \
    {app-docker-img}
----

=== Through the command line

Start Cerbos with `--set=telemetry.disabled=true` command line flag.

.With the binary
[source,sh,subs="attributes"]
----
./{app-name} server --config=/path/to/.cerbos.yaml --set=telemetry.disabled=true
----

.With the container
[source,sh,subs="attributes"]
----
docker run -i -t -p 3592:3592 \
    {app-docker-img} \
    server --set=telemetry.disabled=true
----
