include::ROOT:partial$attributes.adoc[]

= Tracing block

Cerbos supports distributed tracing to provide insights into application performance and request lifecycle. To enable tracing, set `sampleProbability` to a value between 0.0 and 1.0. Setting the probability to 1.0 makes Cerbos capture tracing information for all requests and setting it to 0.0 disables capturing any traces.

The system to export the trace data must be specified using the `exporter` setting. Currently link:https://www.jaegertracing.io[Jaeger] and link:https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md[OTLP collectors] are supported. If using Jaeger, traces can be sent to either a Jaeger Agent (compact Thrift format) or a Jaeger Collector (Thrift format).


.OpenTelemetry
****
link:https://opentelemetry.io[OpenTelemetry] is the evolving standard for observability. Cerbos supports OpenTelemetry with a few caveats due to limitations in the current Go implementation of OpenTelemetry.


* gRPC clients should use the link:https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/propagators/opencensus[OpenCensus binary propagation format] for distributed traces.

* Metrics are not yet supported.

****

== Jaeger [Deprecated]

NOTE: Jaeger now supports OTLP and it's recommended to use the OTLP exporter instead. The native Jaeger exporter is deprecated and will be removed in a future release.


.Send trace data to Jaeger Agent (compact Thrift)
[source,yaml,linenums]
----
tracing:
  serviceName: cerbos
  sampleProbability: 0.5
  exporter: jaeger
  jaeger:
    agentEndpoint: "localhost:6831"
----

.Send trace data to Jaeger Collector (Thrift)
[source,yaml,linenums]
----
tracing:
  serviceName: cerbos
  sampleProbability: 0.5
  exporter: jaeger
  jaeger:
    collectorEndpoint: "http://localhost:14268/api/traces"
----

[#otlp]
== OTLP

.Send trace data to an OTLP collector
[source,yaml,linenums]
----
tracing:
  serviceName: cerbos
  sampleProbability: 0.5
  exporter: otlp
  otlp:
    protocol: grpc # or http
    collectorEndpoint: "otel:4317"
----
