include::ROOT:partial$attributes.adoc[]

= Tracing block

Cerbos supports distributed tracing to provide insights into application performance and request lifecycle. To enable tracing, set `sampleProbability` to a value between 0.0 and 1.0. Setting the probability to 1.0 makes Cerbos capture tracing information for all requests and setting it to 0.0 disables capturing any traces. 

The system to export the trace data must be specified using the `exporter` setting. Currently only link:https://www.jaegertracing.io[Jaeger] is supported. Traces can be sent to either Jaeger Agent (compact Thrift format) or Jaeger Collector (Thrift format). 


.OpenTelemetry
****
link:https://opentelemetry.io[OpenTelemetry] is the evolving standard for observability. Cerbos supports OpenTelemetry with a few caveats due to limitations in the current Go implementation of OpenTelemetry. 


* gRPC clients should use the link:https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/propagators/opencensus[OpenCensus binary propagation format] for distributed traces.

* Metrics are not yet supported. 

****

== Jaeger

.Send trace data to Jaeger Agent (compact Thrift)
[source,yaml,linenums]
----
tracing:
  sampleProbability: 0.5
  exporter: jaeger
  jaeger: 
    serviceName: cerbos 
    agentEndpoint: "localhost:6831" 
----

.Send trace data to Jaeger Collector (Thrift)
[source,yaml,linenums]
----
tracing:
  sampleProbability: 0.5
  exporter: jaeger
  jaeger: 
    serviceName: cerbos 
    collectorEndpoint: "http://localhost:14268/api/traces"
----

