---
snapshot:
  name_template: '{{ incminor .Version }}-prerelease'

git:
  ignore_tags:
    - 'api/genpb/*'

builds:
  - main: ./cmd/cerbos
    binary: cerbos
    id: "cerbos"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/cerbos/cerbos/internal/util.Version={{.Version}} -X github.com/cerbos/cerbos/internal/util.Commit={{.FullCommit}} -X github.com/cerbos/cerbos/internal/util.BuildDate={{.Date}} -X github.com/cerbos/cerbos/internal/telemetry.WriteKey={{.Env.TELEMETRY_WRITE_KEY}} -X github.com/cerbos/cerbos/internal/telemetry.DataPlaneURL={{.Env.TELEMETRY_URL}}

  - main: ./cmd/cerbosctl
    binary: cerbosctl
    id: "cerbosctl"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/cerbos/cerbos/internal/util.Version={{.Version}} -X github.com/cerbos/cerbos/internal/util.Commit={{.FullCommit}} -X github.com/cerbos/cerbos/internal/util.BuildDate={{.Date}} -X github.com/cerbos/cerbos/internal/telemetry.WriteKey={{.Env.TELEMETRY_WRITE_KEY}} -X github.com/cerbos/cerbos/internal/telemetry.DataPlaneURL={{.Env.TELEMETRY_URL}}
universal_binaries:
  - id: "cerbos"
    replace: false
    name_template: "cerbos"
  - id: "cerbosctl"
    replace: false
    name_template: "cerbosctl"
archives:
  - id: cerbos
    builds:
      - cerbos
      - cerbosctl
    name_template: 'cerbos_{{ .Version }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  - id: cerbosctl
    builds:
      - cerbosctl
    name_template: 'cerbosctl_{{ .Version }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
nfpms:
  - id: cerbos
    package_name: cerbos
    builds:
      - cerbos
      - cerbosctl
    vendor: Zenauth Ltd.
    homepage: https://cerbos.dev
    maintainer: "Cerbos Authors <help@cerbos.dev>"
    license: Apache 2.0
    formats:
      - deb
      - rpm
    scripts:
      postinstall: deploy/linux/scripts/post-install.sh
      preremove: deploy/linux/scripts/pre-remove.sh
    contents:
      - src: deploy/linux/conf/cerbos.yaml
        dst: /etc/cerbos.yaml
        type: config|noreplace
      - src: deploy/linux/unit/cerbos.service
        dst: /etc/systemd/system/cerbos.service
      - dst: /var/cerbos/policies
        type: dir

signs:
  - cmd: cosign
    args:
      - sign-blob
      - --yes
      - --rekor-url
      - https://rekor.sigstore.dev/
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: all

dockers:
  - id: cerbos-amd64
    dockerfile: Dockerfile.cerbos
    image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-amd64"
      - "ghcr.io/cerbos/cerbos:latest-amd64"
      - "ghcr.io/cerbos/cerbos:dev-amd64"
      - "docker.io/cerbos/cerbos:{{ .Version }}-amd64"
      - "docker.io/cerbos/cerbos:latest-amd64"
      - "docker.io/cerbos/cerbos:dev-amd64"
    ids:
      - cerbos
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"

  - id: cerbos-arm64
    dockerfile: Dockerfile.cerbos
    image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-arm64"
      - "ghcr.io/cerbos/cerbos:latest-arm64"
      - "ghcr.io/cerbos/cerbos:dev-arm64"
      - "docker.io/cerbos/cerbos:{{ .Version }}-arm64"
      - "docker.io/cerbos/cerbos:latest-arm64"
      - "docker.io/cerbos/cerbos:dev-arm64"
    ids:
      - cerbos
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"

  - id: cerbosctl-amd64
    dockerfile: Dockerfile.cerbosctl
    image_templates:
      - "ghcr.io/cerbos/cerbosctl:{{ .Version }}-amd64"
      - "ghcr.io/cerbos/cerbosctl:latest-amd64"
      - "ghcr.io/cerbos/cerbosctl:dev-amd64"
      - "docker.io/cerbos/cerbosctl:{{ .Version }}-amd64"
      - "docker.io/cerbos/cerbosctl:latest-amd64"
      - "docker.io/cerbos/cerbosctl:dev-amd64"
    ids:
      - cerbosctl
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name=cerbosctl"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"

  - id: cerbosctl-arm64
    dockerfile: Dockerfile.cerbosctl
    image_templates:
      - "ghcr.io/cerbos/cerbosctl:{{ .Version }}-arm64"
      - "ghcr.io/cerbos/cerbosctl:latest-arm64"
      - "ghcr.io/cerbos/cerbosctl:dev-arm64"
      - "docker.io/cerbos/cerbosctl:{{ .Version }}-arm64"
      - "docker.io/cerbos/cerbosctl:latest-arm64"
      - "docker.io/cerbos/cerbosctl:dev-arm64"
    ids:
      - cerbosctl
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name=cerbosctl"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/cerbos/cerbos:{{ .Version }}"
    image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-amd64"
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-arm64"

  - name_template: "ghcr.io/cerbos/cerbosctl:{{ .Version }}"
    image_templates:
      - "ghcr.io/cerbos/cerbosctl:{{ .Version }}-amd64"
      - "ghcr.io/cerbos/cerbosctl:{{ .Version }}-arm64"

  - name_template: "ghcr.io/cerbos/cerbos:latest"
    image_templates:
      - "ghcr.io/cerbos/cerbos:latest-amd64"
      - "ghcr.io/cerbos/cerbos:latest-arm64"

  - name_template: "ghcr.io/cerbos/cerbosctl:latest"
    image_templates:
      - "ghcr.io/cerbos/cerbosctl:latest-amd64"
      - "ghcr.io/cerbos/cerbosctl:latest-arm64"

  - name_template: "ghcr.io/cerbos/cerbos:dev"
    image_templates:
      - "ghcr.io/cerbos/cerbos:dev-amd64"
      - "ghcr.io/cerbos/cerbos:dev-arm64"

  - name_template: "ghcr.io/cerbos/cerbosctl:dev"
    image_templates:
      - "ghcr.io/cerbos/cerbosctl:dev-amd64"
      - "ghcr.io/cerbos/cerbosctl:dev-arm64"

  - name_template: "docker.io/cerbos/cerbos:{{ .Version }}"
    image_templates:
      - "docker.io/cerbos/cerbos:{{ .Version }}-amd64"
      - "docker.io/cerbos/cerbos:{{ .Version }}-arm64"

  - name_template: "docker.io/cerbos/cerbosctl:{{ .Version }}"
    image_templates:
      - "docker.io/cerbos/cerbosctl:{{ .Version }}-amd64"
      - "docker.io/cerbos/cerbosctl:{{ .Version }}-arm64"

  - name_template: "docker.io/cerbos/cerbos:latest"
    image_templates:
      - "docker.io/cerbos/cerbos:latest-amd64"
      - "docker.io/cerbos/cerbos:latest-arm64"

  - name_template: "docker.io/cerbos/cerbosctl:latest"
    image_templates:
      - "docker.io/cerbos/cerbosctl:latest-amd64"
      - "docker.io/cerbos/cerbosctl:latest-arm64"

  - name_template: "docker.io/cerbos/cerbos:dev"
    image_templates:
      - "docker.io/cerbos/cerbos:dev-amd64"
      - "docker.io/cerbos/cerbos:dev-arm64"

  - name_template: "docker.io/cerbos/cerbosctl:dev"
    image_templates:
      - "docker.io/cerbos/cerbosctl:dev-amd64"
      - "docker.io/cerbos/cerbosctl:dev-arm64"

docker_signs:
  - id: sign-images
    cmd: cosign
    args:
      - sign
      - --yes
      - --rekor-url
      - https://rekor.sigstore.dev/
      - "${artifact}"
    artifacts: all
    output: true

brews:
  - repository:
      owner: cerbos
      name: homebrew-tap
      branch: "release_{{ .Version }}"
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        base:
          branch: main

    folder: Formula
    ids:
      - cerbos
    homepage: "https://cerbos.dev"
    description: "Cerbos is the open core, language-agnostic, scalable authorization solution that makes user permissions and authorization simple to implement and manage by writing context-aware access control policies for your application resources."
    license: "Apache-2.0"
checksum:
  name_template: 'checksums.txt'
release:
  header: |-
    Cerbos {{ .Version }}
    ---------------------

    View the full release notes at https://docs.cerbos.dev/cerbos/latest/releases/v{{ .Version }}.html

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: 'feat(?:\(.+?\))?!?:'
      order: 5
    - title: Enhancements
      regexp: 'enhancement(?:\(.+?\))?!?:'
      order: 10
    - title: Bug fixes
      regexp: 'fix(?:\(.+?\))?!?:'
      order: 15
    - title: Documentation
      regexp: 'docs(?:\(.+?\))?!?:'
      order: 20
    - title: Chores
      regexp: 'chore(?:\(.+?\))?!?:'
      order: 25
    - title: Others
      order: 100
