builds:
  - main: ./cmd/cerbos
    binary: cerbos
    id: "cerbos"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/cerbos/cerbos/internal/util.Version={{.Version}} -X github.com/cerbos/cerbos/internal/util.commit={{.Commit}} -X github.com/cerbos/cerbos/internal/util.BuildDate={{.Date}}  
  - main: ./cmd/cerbosctl
    binary: cerbosctl
    id: "cerbosctl"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/cerbos/cerbos/internal/util.Version={{.Version}} -X github.com/cerbos/cerbos/internal/util.commit={{.Commit}} -X github.com/cerbos/cerbos/internal/util.BuildDate={{.Date}}  
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
dockers:
  - image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-amd64"
      - "cerbos.jfrog.io/containers/cerbos:{{ .Version }}-amd64"
      - "ghcr.io/cerbos/cerbos:dev-amd64"
    goarch: amd64
    use: buildx
    extra_files:
      - conf.default.yaml
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"

  - image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-arm64"
      - "cerbos.jfrog.io/containers/cerbos:{{ .Version }}-arm64"
      - "ghcr.io/cerbos/cerbos:dev-arm64"
    goarch: arm64
    use: buildx
    extra_files:
      - conf.default.yaml
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "ghcr.io/cerbos/cerbos:{{ .Version }}"
    image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-amd64"
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-arm64"
  - name_template: "cerbos.jfrog.io/containers/cerbos:{{ .Version }}"
    image_templates:
      - "cerbos.jfrog.io/containers/cerbos:{{ .Version }}-amd64"
      - "cerbos.jfrog.io/containers/cerbos:{{ .Version }}-arm64"
  - name_template: "ghcr.io/cerbos/cerbos:dev"
    image_templates:
      - "ghcr.io/cerbos/cerbos:dev-amd64"
      - "ghcr.io/cerbos/cerbos:dev-arm64"
artifactories:
  - name: prod
    mode: archive
    target: https://cerbos.jfrog.io/artifactory/binaries
checksum:
  name_template: 'checksums.txt'
release:
  header: |-
    Cerbos {{ .Version }}
    ---------------------
    
    View the full release notes at https://docs.cerbos.dev/cerbos/latest/releases/v{{ .Version }}.html 

changelog:
  sort: asc
  filters:
    exclude:
      - '^ci:'
      - '^chore'
      - '^docs:'
      - '^test:'
