before:
  hooks:
    - make generate
    - make test
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/cerbos/cerbos/pkg/util.Version={{.Version}} -X github.com/cerbos/cerbos/pkg/util.commit={{.Commit}} -X github.com/cerbos/cerbos/pkg/util.BuildDate={{.Date}}  
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
dockers:
  - image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-amd64"
    goarch: amd64
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-arm64"
    goarch: arm64
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "ghcr.io/cerbos/cerbos:{{ .Version }}"
    image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-amd64"
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-arm64"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
