before:
  hooks:
    - make generate
    - make lint
    - make test
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/cerbos/cerbos/pkg/util.Version={{.Version}} -X github.com/cerbos/cerbos/pkg/util.commit={{.Commit}} -X github.com/cerbos/cerbos/pkg/util.BuildDate={{.Date}}  
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
dockers:
  - image_templates:
      - "cerbos/cerbos:latest"
      - "cerbos/cerbos:{{ .Version }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
