builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/cerbos/cerbos/internal/util.Version={{.Version}} -X github.com/cerbos/cerbos/internal/util.commit={{.Commit}} -X github.com/cerbos/cerbos/internal/util.BuildDate={{.Date}}  
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
dockers:
  - image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-amd64"
      - "cerbos.jfrog.io/containers/cerbos:{{ .Version }}-amd64"
    goarch: amd64
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - conf.default.yaml

  - image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-arm64"
      - "cerbos.jfrog.io/containers/cerbos:{{ .Version }}-arm64"
    goarch: arm64
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/arm64"
    extra_files:
      - conf.default.yaml
docker_manifests:
  - name_template: "ghcr.io/cerbos/cerbos:{{ .Version }}"
    image_templates:
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-amd64"
      - "ghcr.io/cerbos/cerbos:{{ .Version }}-arm64"
  - name_template: "cerbos.jfrog.io/containers/cerbos:{{ .Version }}"
    image_templates:
      - "cerbos.jfrog.io/containers/cerbos:{{ .Version }}-amd64"
      - "cerbos.jfrog.io/containers/cerbos:{{ .Version }}-arm64"
artifactories:
  - name: prod
    mode: archive
    target: https://cerbos.jfrog.io/artifactory/binaries
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
