gomod:
  proxy: true

snapshot:
  name_template: '{{ incminor .Version }}-prerelease'

builds:
  - main: ./cmd/cerbos
    binary: cerbos
    id: "cerbos"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X github.com/cerbos/cerbos/internal/util.Version={{.Version}} -X github.com/cerbos/cerbos/internal/util.Commit={{.FullCommit}} -X github.com/cerbos/cerbos/internal/util.BuildDate={{.Date}}  
  - main: ./cmd/cerbosctl
    binary: cerbosctl
    id: "cerbosctl"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X github.com/cerbos/cerbos/internal/util.Version={{.Version}} -X github.com/cerbos/cerbos/internal/util.Commit={{.FullCommit}} -X github.com/cerbos/cerbos/internal/util.BuildDate={{.Date}}  
universal_binaries:
  - id: "cerbos"
    replace: false
    name_template: "cerbos"
  - id: "cerbosctl"
    replace: false
    name_template: "cerbosctl"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
dockers:
  - image_templates:
      - "ghcr.io/cerbos/cerbos:latest"
      - "ghcr.io/cerbos/cerbos:{{ .Version }}"
    extra_files:
      - conf.default.yaml
checksum:
  disable: true
changelog:
  skip: true
