dir: internal/test/mocks
filename: "{{.InterfaceName}}.go"
pkgname: mocks
structname: "{{.InterfaceName}}"
template: testify
template-data:
  boilerplate-file: hack/copyright_header.txt
packages:
  github.com/cerbos/cerbos/internal/audit/hub:
    interfaces:
      IngestSyncer: {}

  github.com/cerbos/cerbos/internal/storage:
    interfaces:
      Store: {}

  github.com/cerbos/cerbos/internal/storage/hub:
    interfaces:
      ClientProvider: {}
      ClientV1: {}
      ClientV2: {}

  github.com/cerbos/cerbos/internal/storage/index:
    interfaces:
      Index: {}

  github.com/cerbos/cloud-api/bundle:
    interfaces:
      WatchHandle: {}
