name: Publish docs

description: Publish docs to Netlify

inputs:
  auth_token:
    description: Netlify authentication token
    required: true

  site_id:
    description: Netlify site ID
    required: true

runs:
  using: composite

  steps:
    - name: Install Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version-file: .node-version

    - name: Publish docs to Netlify
      shell: bash
      run: npx --package=netlify-cli -- netlify deploy --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.auth_token }}
        NETLIFY_SITE_ID: ${{ inputs.site_id }}
