name: ⭐️ Feature Request
description: Request a feature
title: "<title>"
labels: [enhancement, performance, chore, feature]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature you have requested.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Feature description
    description: A concise description of what you're requesting as a feature.
  validations:
    required: true
- type: textarea
  attributes:
    label: How to solve this
    description: If you have any ideas that how we may solve the problem, feel free to add here.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
