[[configuration]]
= Configuration

The Cerbos server is configured with a YAML file. Start the server by passing the configuration file using the `--config` flag.

[source,yaml,linenums]
----
---
server:
  httpListenAddr: ":3592" 
  grpcListenAddr: ":3593"
  tls: # Optional
    cert: /path/to/certificate
    key: /path/to/private_key
    caCert: /path/to/CA_certificate # Optional

storage:
  driver: "disk" # Valid values are "disk" or "git"
  disk: # Only required if "driver" is "disk"
    directory: pkg/test/testdata/store
    readOnly: true # Set to false if you want to write new policies to disk through the API
  git: # Only required if the "driver" is "git"
    protocol: file # Valid values are "file", "ssh", "https"
    url: file://${HOME}/tmp/cerbos/policies 
    branch: policies # Branch that should be used as the source. Defaults to "master"
    subDir: policies # Set this if the policies are stored in a subdirectory
    checkoutDir: ${HOME}/tmp/cerbos/work # Work directory of the server
    updatePollInterval: 60s # How often the source git repo should be polled for updates
    https: # Only required if the "protocol" is "https"
      username: charithe
      password: ${GITHUB_TOKEN}
    ssh: # Only required if the "protocol" is "ssh"
      user: git
      privateKeyFile: ${HOME}/.ssh/id_rsa
----


== Server configuration

By default the server will start an HTTP server on port `3592` and a gRPC server on `3593` that will listen on all available interfaces. You can change these defaults and optionally configure TLS using the `server` block.

.Default behaviour: listen on all available interfaces
[source,yaml,linenums]
----
server:
  httpListenAddr: ":3592" 
  grpcListenAddr: ":3593"
----

.Listen on a specific interface
[source,yaml,linenums]
----
server:
  httpListenAddr: "192.168.0.17:3592" 
  grpcListenAddr: "192.168.0.17:3593"
----


.Listen on a Unix domain socket
[source,yaml,linenums]
----
server:
  httpListenAddr: "unix:/var/sock/cerbos.http" 
  grpcListenAddr: "unix:/var/sock/cerbos.grpc"
----

=== Transport layer security

You can enable transport layer security (TLS) by defining the paths to the certificate and key file in the `TLS` section.

[source,yaml,linenums]
----
server:
  httpListenAddr: ":3592" 
  grpcListenAddr: ":3593"
  tls: 
    cert: /path/to/certificate
    key: /path/to/private_key
----

NOTE: For production use cases that require automatic certificate reloading, workload identities and other advanced features, we recommend running a proxy server such as link:https://www.envoyproxy.io[Envoy], link:https://github.com/ghostunnel/ghostunnel[Ghostunnel] or link:https://traefik.io[Traefik] in front of the Cerbos server. 
