= Introduction

Marketing speak here.

== Policies

There are three kinds of policies.

Derived roles:: Traditional RBAC role are statically defined and have no context awareness. Derived roles allow augmenting static roles with contextual data to provide more fine-grained control.
Resource policies:: Defines rules for actions that can be performed on a given resource. A resource is essentially an abstract unit of work as defined by the application. For example, in an HR application, a resource can be as coarse-grained as a full employee record or as fine-grained as a single field in a record. 
Principal policies:: Defines overrides for a particular principal (user, application)

=== Derived roles

[source,yaml,linenums]
----
---
apiVersion: "cerbos.dev/v1"
description: |-
  Common dynamic roles used within the Apatr app
derived_roles:
  name: apatr_common_roles <1>
  definitions:
    - name: owner <2>
      parentRoles: ["user"] <3>
      computation:
        match:
          expr:
            - request.resource.attr.owner == request.principal.id <4>

    - name: abuse_moderator
      parentRoles: ["moderator"]
      computation:
        match:
          expr:
            - request.resource.attr.flagged == true
----
<1> Name to use when importing this set of derived roles
<2> Descriptive name for this derived role
<3> The static roles (from the identity provider) to which this derived role applies to
<4> An (optional) set of expressions that should evaluate to true for this role to activate


=== Resource roles

[source,yaml,linenums]
----
---
apiVersion: cerbos.dev/v1
resourcePolicy:
  version: "default" <1>
  importDerivedRoles:
    - apatr_common_roles <2>
  resource: "album:object"  <3>
  rules:
    - action: '*' <4>
      effect: EFFECT_ALLOW
      derivedRoles:
        - owner <5>

    - action: view
      effect: EFFECT_ALLOW
      roles:
        - user <6>
      condition:
        match:
          expr:
            - request.resource.attr.public == true

    - action: view
      effect: EFFECT_ALLOW
      derivedRoles:
        - abuse_moderator

    - action: delete
      effect: EFFECT_ALLOW
      derivedRoles:
        - abuse_moderator
----
<1> Version of this policy. Policies are uniquely identified by the resource name and version pair. You can have multiple policy versions for the same resource (e.g. production vs. staging). `default` version is special as it is the fallback when no version is specified.
<2> Import a set of derived roles
<3> Name of the resource to which this policy applies
<4> Actions can contain wildcards. They are segmented by colons `:` (e.g. `a:*:d` would match `a:x:d` but not `a:x`)
<5> This rule applies to a derived role
<6> Rules can also refer directly to static roles


=== Principal roles

[source,yaml,linenums]
----
---
apiVersion: "cerbos.dev/v1"
principalPolicy:
  principal: daffy_duck <1>
  version: "dev" <2>
  rules:
    - resource: leave_request <3>
      actions:
        - action: "*"
          condition:
            match:
              expr:
                - "request.resource.attr.dev_record == true"
          effect: EFFECT_ALLOW

    - resource: salary_record 
      actions:
        - action: "*"
          effect: EFFECT_DENY
----
<1> Principal to whom this policy applies
<2> Version of this policy. Policies are uniquely identified by the principal name and version pair. You can have multiple policy versions for the same principal (e.g. production vs. staging). `default` version is special as it is the fallback when no version is specified.
<3> Resource to which this override applies


== Request format

[source,json,linenums]
----
{
  "requestId":  "test01", <1>
  "action":  "view", <2>
  "resource":  {
    "version": "dev", <3>
    "name":  "album:object", <4>
    "attr":  { <5>
      "owner":  "alicia",
      "id":  "XX125",
      "public": false,
      "tags": ["x", "y"],
      "flagged": false
    }
  },
  "principal":  {
    "id":  "alicia", <6>
    "version": "dev", <7>
    "roles":  ["user"], <8>
    "attr": {
      "geography": "GB"
    }
  }
}
----
<1> Request ID can be anything that uniquely identifies a request
<2> Action being performed on the resource
<3> Resource policy version that should be used. Optional.
<4> Resource name
<5> Free-form context data about this resource
<6> ID of the principal performing the action
<7> Principal policy version that should be used. Optional.
<8> Static roles that are assigned to this principal

