{{- if .Values.certManager.certSpec -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cerbos.fullname" . }}
  labels:
    {{- include "cerbos.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.certManager.certSpec | nindent 2 }}
{{- end -}}
