apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cerbos.fullname" . }}
  labels:
    {{- include "cerbos.labels" . | nindent 4 }}
data:
    ".cerbos.yaml": |-
    {{- include "cerbos.config" . | nindent 8 }}
