// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cerbos/schema/v1/schema.proto

package schemav1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Schema with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Schema) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetApiVersion() != "api.cerbos.dev/v1" {
		return SchemaValidationError{
			field:  "ApiVersion",
			reason: "value must equal api.cerbos.dev/v1",
		}
	}

	if !_Schema_SchemaVersion_Pattern.MatchString(m.GetSchemaVersion()) {
		return SchemaValidationError{
			field:  "SchemaVersion",
			reason: "value does not match regex pattern \"^[[:word:]]+$\"",
		}
	}

	// no validation rules for Disabled

	// no validation rules for Description

	if v, ok := interface{}(m.GetPrincipalSchema()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SchemaValidationError{
				field:  "PrincipalSchema",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetResourceSchema()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SchemaValidationError{
				field:  "ResourceSchema",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// SchemaValidationError is the validation error returned by Schema.Validate if
// the designated constraints aren't met.
type SchemaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SchemaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SchemaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SchemaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SchemaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SchemaValidationError) ErrorName() string { return "SchemaValidationError" }

// Error satisfies the builtin error interface
func (e SchemaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSchema.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SchemaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SchemaValidationError{}

var _Schema_SchemaVersion_Pattern = regexp.MustCompile("^[[:word:]]+$")

// Validate checks the field values on ResourceSchema with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ResourceSchema) Validate() error {
	if m == nil {
		return nil
	}

	for key, val := range m.GetSchemas() {
		_ = val

		// no validation rules for Schemas[key]

		if v, ok := interface{}(val).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResourceSchemaValidationError{
					field:  fmt.Sprintf("Schemas[%v]", key),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ResourceSchemaValidationError is the validation error returned by
// ResourceSchema.Validate if the designated constraints aren't met.
type ResourceSchemaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceSchemaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceSchemaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceSchemaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceSchemaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceSchemaValidationError) ErrorName() string { return "ResourceSchemaValidationError" }

// Error satisfies the builtin error interface
func (e ResourceSchemaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceSchema.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceSchemaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceSchemaValidationError{}

// Validate checks the field values on JSONSchemaProps with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *JSONSchemaProps) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Schema

	// no validation rules for Ref

	// no validation rules for Description

	// no validation rules for Type

	// no validation rules for Format

	// no validation rules for Title

	for key, val := range m.GetProperties() {
		_ = val

		// no validation rules for Properties[key]

		if v, ok := interface{}(val).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return JSONSchemaPropsValidationError{
					field:  fmt.Sprintf("Properties[%v]", key),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for key, val := range m.GetDefinitions() {
		_ = val

		// no validation rules for Definitions[key]

		if v, ok := interface{}(val).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return JSONSchemaPropsValidationError{
					field:  fmt.Sprintf("Definitions[%v]", key),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// JSONSchemaPropsValidationError is the validation error returned by
// JSONSchemaProps.Validate if the designated constraints aren't met.
type JSONSchemaPropsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JSONSchemaPropsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JSONSchemaPropsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JSONSchemaPropsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JSONSchemaPropsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JSONSchemaPropsValidationError) ErrorName() string { return "JSONSchemaPropsValidationError" }

// Error satisfies the builtin error interface
func (e JSONSchemaPropsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJSONSchemaProps.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JSONSchemaPropsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JSONSchemaPropsValidationError{}
