---
# https://docs.cerbos.dev/cerbos/latest/configuration/auxdata.html
# WARNING: Disabling JWT verification is not recommended because it makes the system
# insecure by forcing Cerbos to evaluate policies using potentially tampered data.
auxData:
  jwt:
    disableVerification: true

server:
  httpListenAddr: "unix:/tmp/cerbos.http.sock"
  grpcListenAddr: "unix:/tmp/cerbos.grpc.sock"

storage:
  driver: "disk"
  disk:
    directory: /var/task/policies
