include::ROOT:partial$attributes.adoc[]

= The Cerbos API

include::ROOT:partial$version-check.adoc[]


The main API endpoint for making policy decisions is the xref:#check-resources[`/api/check/resources` REST endpoint] (`cerbos.svc.v1.CerbosService/CheckResources` RPC in the gRPC API). You can browse a xref:attachment$cerbos-api.html[static version of the Cerbos OpenAPI specification on this site,window=_blank]. To interactively explore the API, launch a Cerbos instance and access the root directory of the HTTP endpoint using a browser.


[source,sh,subs="attributes"]
----
docker run --rm --name cerbos -p 3592:3592 -p 3593:3593 {app-docker-img}
----

Navigate to link:http://localhost:3592/[] using your browser to explore the Cerbos API documentation.

Alternatively, you can explore the API using the following methods as well:

* Using an OpenAPI-compatible software like link:https://www.postman.com[Postman] or link:https://insomnia.rest[Insomnia] to explore the Cerbos OpenAPI spec available at http://localhost:3592{cerbos-openapi-schema}.
* Using link:https://github.com/fullstorydev/grpcurl[grpcurl] or any other tool that supports link:https://github.com/grpc/grpc/blob/master/doc/server-reflection.md[gRPC server reflection] API to explore the gRPC API exposed on port 3593.

== Client SDKs

* image:go.svg[alt="Go",width=40,height=40,link="https://pkg.go.dev/github.com/cerbos/cerbos-sdk-go/cerbos"]link:https://pkg.go.dev/github.com/cerbos/cerbos-sdk-go/cerbos[&ensp;Go]
* image:java.svg[alt="Java",width=40,height=40,link="https://github.com/cerbos/cerbos-sdk-java"]link:https://github.com/cerbos/cerbos-sdk-java[&ensp;Java]
* image:javascript.svg[alt="JavaScript",width=40,height=40,link="https://github.com/cerbos/cerbos-sdk-javascript"]link:https://github.com/cerbos/cerbos-sdk-javascript[&ensp;JavaScript]
* image:dot-net.svg[alt=".NET",width=40,height=40,link="https://github.com/cerbos/cerbos-sdk-net"]link:https://github.com/cerbos/cerbos-sdk-net[&ensp;.NET]
* image:laravel.svg[alt="Laravel",width=40,height=40,link="https://github.com/cerbos/cerbos-sdk-laravel"]link:https://github.com/cerbos/cerbos-sdk-laravel[&ensp;Laravel]
* image:php.svg[alt="PHP",width=40,height=40,link="https://github.com/cerbos/cerbos-sdk-php"]link:https://github.com/cerbos/cerbos-sdk-php[&ensp;PHP]
* image:python.svg[alt="Python",width=40,height=40,link="https://github.com/cerbos/cerbos-sdk-python"]link:https://github.com/cerbos/cerbos-sdk-python[&ensp;Python]
* image:ruby.svg[alt="Ruby",width=40,height=40,link="https://github.com/cerbos/cerbos-sdk-ruby"]link:https://github.com/cerbos/cerbos-sdk-ruby[&ensp;Ruby]
* image:rust.svg[alt="Rust",width=40,height=40,link="https://github.com/cerbos/cerbos-sdk-rust"]link:https://github.com/cerbos/cerbos-sdk-rust[&ensp;Rust]

Other languages coming soon

== Demos

NOTE: Demos are constantly being added or updated by the Cerbos team. Visit https://github.com/orgs/cerbos/repositories?language=&q=demo&sort=&type=all for the latest list.

* link:https://github.com/cerbos/demo-python[Application (Python)]
* link:https://github.com/cerbos/demo-graphql[GraphQL Service (NodeJS)]
* link:https://github.com/cerbos/demo-rest[REST Service (Go)]

.Get help
****

* link:http://go.cerbos.io/slack[Join the Cerbos community on Slack]
* mailto:help@cerbos.dev[Email us at help@cerbos.dev]

****

== Request and response formats

[#check-resources]
=== `CheckResources` (`/api/check/resources`)

This is the main API entrypoint for checking permissions for a set of resources.

.Request
[source,json,linenums]
----
{
  "requestId": "test", <1>
  "principal": {
    "id": "alice", <2>
    "policyVersion": "20210210", <3>
    "scope": "acme.corp", <4>
    "roles": [ <5>
      "employee"
    ],
    "attr": { <6>
      "department": "accounting",
      "geography": "GB",
      "team": "design"
    }
  },
  "resources": [ <7>
    {
      "resource": {
        "id": "XX125", <8>
        "kind": "leave_request", <9>
        "policyVersion": "20210210", <10>
        "scope": "acme.corp", <11>
        "attr": { <12>
          "department": "accounting",
          "geography": "GB",
          "id": "XX125",
          "owner": "john",
          "team": "design"
        }
      },
      "actions": [ <13>
        "view:public",
        "approve",
        "create"
      ]
    }
  ],
  "auxData": { <14>
    "jwt": {
        "token": "xxx.yyy.zzz", <15>
        "keySetId": "ks1" <16>
    }
  },
  "includeMeta": true <17>
}
----
<1> Request ID is an optional, application-provided identifier useful for correlating logs.
<2> ID of the principal whose permissions are being checked. This usually comes from the identity provider (IdP).
<3> Principal policy version. Optional. The server falls back to the xref:configuration:engine.adoc[configured default version] if this is not specified.
<4> Principal policy scope. Optional. See xref:policies:scoped_policies.adoc[].
<5> The roles attached to this principal by the identity provider.
<6> Free-form context data about this principal. Policy rule conditions are evaluated based on these values.
<7> List of resources the principal is attempting to access. Up to 50 resources may be provided in a single request by default. This xref:configuration:server.adoc#request-limits[limit can be configured].
<8> ID of the resource.
<9> Resource kind. This is used to determine the resource policy that applies to this resource.
<10> Resource policy version. Optional. The server falls back to the xref:configuration:engine.adoc[configured default version] if this is not specified.
<11> Resource policy scope. Optional. See xref:policies:scoped_policies.adoc[].
<12> Free-form context data about this resource. Policy rule conditions are evaluated based on these values.
<13> List of actions being performed on the resource. Up to 50 actions per resource may be provided by default. This xref:configuration:server.adoc#request-limits[limit can be configured].
<14> Optional section for providing auxiliary data.
<15> JWT to use as an auxiliary data source.
<16> ID of the keyset to use to verify the JWT. Optional if only a single xref:configuration:auxdata.adoc[keyset is configured].
<17> Optional flag to receive metadata about request evaluation.



.Response
[source,json,linenums]
----
{
  "requestId": "test", <1>
  "results": [ <2>
    {
      "resource": { <3>
        "id": "XX125",
        "kind": "leave_request",
        "policyVersion": "20210210",
        "scope": "acme.corp"
      },
      "actions": { <4>
        "view:public": "EFFECT_ALLOW",
        "approve": "EFFECT_DENY"
      },
      "outputs": [ <5>
        {
          "src": "resource.leave_request.v20210210/acme#rule-001", <6>
          "val": "create_allowed:john" <7>
        },
        {
          "src": "resource.leave_request.v20210210#public-view",
          "val": {
            "id": "john",
            "keys": ["foo", "bar", "baz"]
          }
        }
      ],
      "validationErrors": [ <8>
        {
          "path": "/department",
          "message": "value must be one of \"marketing\", \"engineering\"",
          "source": "SOURCE_PRINCIPAL"
        },
        {
          "path": "/department",
          "message": "value must be one of \"marketing\", \"engineering\"",
          "source": "SOURCE_RESOURCE"
        }
      ],
      "meta": { <9>
        "actions": {
          "view:public": {
            "matchedPolicy": "resource.leave_request.v20210210/acme.corp", <10>
            "matchedScope": "acme" <11>
          },
          "approve": {
            "matchedPolicy": "resource.leave_request.v20210210/acme.corp"
          }
        },
        "effectiveDerivedRoles": [ <12>
          "employee_that_owns_the_record",
          "any_employee"
        ]
      }
    }
  ],
  "cerbosCallId": "01HHENANTHFD5DV3HZGDKB87PJ" <13>
}
----
<1> Request ID that was sent with the request.
<2> List of results. Items are in the same order as they were sent in the request.
<3> Resource identifiers.
<4> Access decisions for each of the actions.
<5> List of outputs from policy evaluation, if there are any. See xref:policies:outputs.adoc[].
<6> Name of the rule that produced the output.
<7> Output value produced by the rule.
<8> Validation errors, if xref:policies:schemas.adoc[schema enforcement] is enabled and the request didn't conform to the schema.
<9> Metadata (if `includeMeta` was true in the request)
<10> Name of the policy that produced the decision for this action.
<11> Name of the scope that was active when the decision was made for the action.
<12> List of derived roles that were activated.
<13> The call ID generated by Cerbos and stored in the audit log for this request.


[#resources-query-plan]
=== `PlanResources` (`/api/plan/resources`)

Produces a query plan that can be used to obtain a list of resources that a principal is allowed to perform a particular action on.

.Request
[source,json,linenums]
----
{
  "requestId":  "test01", <1>
  "action":  "approve", <2>
  "actions":  ["approve", "view"], <3>
  "resource":  {
    "policyVersion": "dev", <4>
    "kind":  "leave_request", <5>
    "scope": "acme.corp", <6>
    "attr":  { <7>
      "owner":  "alicia"
    }
  },
  "principal":  {
    "id":  "alicia", <8>
    "policyVersion": "dev", <9>
    "scope": "acme.corp", <10>
    "roles":  ["user"], <11>
    "attr": { <12>
      "geography": "GB"
    }
  },
  "includeMeta": true, <13>
  "auxData": { <14>
    "jwt": {
      "token": "xxx.yyy.zzz", <15>
      "keySetId": "ks-1" <16>
    }
  }
}
----
<1> Request ID can be anything that uniquely identifies a request.
<2> Action being performed on the resource instances. Either <2> or <3> is required.
<3> Actions being performed on the resource instances. The query plan is the logical AND of individual query plans for each action. Either <2> or <3> is required.
<4> Resource policy version. Optional. The server falls back to the xref:configuration:engine.adoc[configured default version] if this is not specified.
<5> Resource kind. Required. This value is used to determine the resource policy to evaluate.
<6> Resource scope. Optional. See xref:policies:scoped_policies.adoc[].
<7> Free-form context data about the resources under consideration. The object holds all attributes known about the resource at the time the request. Optional. Policy rule conditions will be (partially) evaluated based on these values. If an effective policy rule condition(s) requires a resource attribute not present in this object, then the response will contain the condition(s) abstract syntax tree.
<8> ID of the principal performing the actions. Required.
<9> Principal policy version. Optional. The server falls back to the xref:configuration:engine.adoc[configured default version] if this is not specified.
<10> Principal scope. Optional. See xref:policies:scoped_policies.adoc[].
<11> Static roles that are assigned to this principal by your identity management system. Required.
<12> Free-form context data about this principal. Policy rule conditions are evaluated based on these values.
<13> An optional flag to signal that the response should include metadata about evaluation. Useful for debugging.
<14> Optional section for providing auxiliary data.
<15> JWT to use as an auxiliary data source.
<16> ID of the keyset to use to verify the JWT. Optional if only a single xref:configuration:auxdata.adoc[keyset is configured].


.Response
[source,json,linenums]
----
{
  "requestId": "test01",
  "action": "approve",
  "resourceKind": "leave_request",
  "policyVersion": "dev",
  "filter": {
    "kind": "KIND_CONDITIONAL", <1>
    "condition": { <2>
        "expression":  {
          "operator":  "eq",
          "operands":  [
            { "variable":  "request.resource.attr.status" },
            { "value":  "PENDING_APPROVAL" }
          ]
        }
    }
  },
  "meta": {
    "filterDebug": "(request.resource.attr.status == \"PENDING_APPROVAL\")" <3>
  },
  "cerbosCallId": "01HHENANTHFD5DV3HZGDKB87PJ" <4>
}
----
<1> Filter kind can be `KIND_ALWAYS_ALLOWED`, `KIND_ALWAYS_DENIED` or `KIND_CONDITIONAL`. See below for description of what these values mean.
<2> Populated only if `kind` is `KIND_CONDITIONAL`. Contains the abstract syntax tree (AST) of the condition that must be satisfied to allow the action.
<3> Condition AST represented as a human readable string. Useful for debugging.
<4> The call ID generated by Cerbos and stored in the audit log for this request.

==== Structure of the `filter` block

The `kind` field defines the filter kind.

`KIND_ALWAYS_ALLOWED`:: The principal is unconditionally allowed to perform the action
`KIND_ALWAYS_DENIED`:: The principal is unconditionally not permitted to perfrom the action
`KIND_CONDITIONAL`:: The principal is allowed to perform the action if the condition is satisfied


The `condition` field holds the AST of the condition that must be satisfied. It is rooted in an expression that has an `operator` (e.g. equals, greater than) and `operands` (e.g. a constant value, a variable or another expression).

.Common Operators
[caption=]
[%header,cols=".^1m,.^4",grid=rows]
|===
| Operator | Description
| add               | Addition (+)
| and               | Logical AND (&&)
| div               | Division (/)
| eq                | Equality (==)
| ge                | Greater than or equal (>=)
| gt                | Greater than (>)
| in                | List membership (in)
| index             | Array or map index
| lambda            | Anonymous function
| le                | Less than or equal (<=)
| list              | List constructor
| lt                | Less than (<)
| mod               | Modulo (%)
| mult              | Multiplication (*)
| ne                | Not equal (!=)
| not               | Logical NOT
| or                | Logical OR
| sub               | Subtract (-)
|===

.Example: `request.resource.attr.status == "PENDING_APPROVAL"`
[source,json,linenums]
----
{
  "expression": {
    "operator": "eq",
    "operands": [
      {
        "variable": "request.resource.attr.status"
      },
      {
        "value": "PENDING_APPROVAL"
      }
    ]
  }
}
----

.Example: `(request.resource.attr.department == "marketing") && (request.resource.attr.team != "design")`
[source,json,linenums]
----
{
  "expression": {
    "operator": "and",
    "operands": [
      {
        "expression": {
          "operator": "eq",
          "operands": [
            {
              "variable": "request.resource.attr.department"
            },
            {
              "value": "marketing"
            }
          ]
        }
      },
      {
        "expression": {
          "operator": "ne",
          "operands": [
            {
              "variable": "request.resource.attr.team"
            },
            {
              "value": "design"
            }
          ]
        }
      }
    ]
  }
}
----

.Example: `request.resource.attr.values.filter(t, t > 0)`
[source,json,linenums]
----
{
  "expression": {
    "operator": "filter",
    "operands": [
      {
        "variable": "request.resource.attr.values"
      },
      {
        "expression": {
          "operator": "lambda",
          "operands": [
            {
              "variable": "t"
            },
            {
              "expression": {
                "operator": "gt",
                "operands": [
                  {
                    "variable": "t"
                  },
                  {
                    "value": 0
                  }
                ]
              }
            }
          ]
        }
      }
    ]
  }
}

----


[#server-info]
=== `ServerInfo` (`/api/server_info`)

Returns Cerbos server version.

.Response
[source,json,linenums]
----
{
  "version": "0.25.0",
  "commit": "6b5a051a160398a3c04370f742e6090fab2ed0b8",
  "buildDate": "2023-02-13T09:31:48Z"
}
----

== Accessing the API

=== Using curl to access the REST API


[source,sh,linenums]
----
cat <<EOF | curl --silent "localhost:3592/api/check/resources?pretty" -d @-
{
  "requestId": "test",
  "principal": {
    "id": "alice",
    "roles": ["employee"],
    "attr": {
      "department": "accounting",
      "geography": "GB",
      "team": "design"
    }
  },
  "resources": [
    {
      "resource": {
        "id": "XX125",
        "kind": "leave_request",
        "attr": {
          "department": "accounting",
          "geography": "GB",
          "id": "XX125",
          "owner": "john",
          "team": "design"
        }
      },
      "actions": [
        "view:public",
        "approve",
        "create"
      ]
    }
  ]
}
EOF
----

=== Using grpcurl to access the gRPC API

[source,sh,linenums]
----
cat <<EOF | grpcurl -plaintext -d @ localhost:3593 cerbos.svc.v1.CerbosService/CheckResources
{
  "requestId": "test",
  "principal": {
    "id": "alice",
    "roles": ["employee"],
    "attr": {
      "department": "accounting",
      "geography": "GB",
      "team": "design"
    }
  },
  "resources": [
    {
      "resource": {
        "id": "XX125",
        "kind": "leave_request",
        "attr": {
          "department": "accounting",
          "geography": "GB",
          "id": "XX125",
          "owner": "john",
          "team": "design"
        }
      },
      "actions": [
        "view:public",
        "approve",
        "create"
      ]
    }
  ]
}
EOF
----


== Generating API clients

The Cerbos OpenAPI specification can be obtained from a running Cerbos instance by accessing link:http://localhost:3592{cerbos-openapi-schema}[]. Cerbos gRPC API definitions are published to the link:https://buf.build/cerbos/cerbos-api[Buf schema registry (BSR)] and can be easily added to your project if you use the link:https://docs.buf.build[Buf build system for protobufs].

=== REST

There are many tools available to generate clients from an OpenAPI specification. https://openapi.tools/#sdk is a good resource for finding a tool suitable for your preferred language.


==== Example: Generating a Java client using OpenAPI Generator

NOTE: link:https://openapi-generator.tech[OpenAPI Generator] has link:https://openapi-generator.tech/docs/generators#client-generators[support for many popular programming languages and frameworks]. Please consult the documentation to find the client generation instructions for your favourite language.


This is an example of using the popular link:https://openapi-generator.tech[OpenAPI Generator] service to generate a Java client API.

* Download the Cerbos OpenAPI specification
+
[source,sh,subs="attributes"]
----
curl -Lo swagger.json http://localhost:3592{cerbos-openapi-schema}
----
+
* Run the OpenAPI Generator
+
[source,sh,subs="attributes"]
----
docker run --rm -v $(pwd):/oas openapitools/openapi-generator-cli generate -i /oas/swagger.json -g java -o /oas/java
----

=== gRPC

**Any language**

You can access the Cerbos protobuf definitions from the link:https://github.com/cerbos/cerbos/tree/main/api[Cerbos source tree]. However, the easiest way to generate client code for your preferred language is to use the link:https://docs.buf.build[Buf build tool] to obtain the published API definitions from the link:https://buf.build/cerbos/cerbos-api[Buf schema registry (BSR)].

* Run `buf export buf.build/cerbos/cerbos-api -o proto` to download the API definitions with dependencies to the `proto` directory.

* You can now use link:https://docs.buf.build/generate-usage[`buf generate`] or `protoc` to generate code using the protobufs available in the `proto` directory.

NOTE: link:https://buf.build/cerbos/cerbos-api/sdks[BSR generated SDKs] feature can be used to download pre-packaged, generated code for supported languages.


**Go**

The link:https://pkg.go.dev/github.com/cerbos/cerbos/client[Cerbos Go SDK] uses the gRPC API to communicate with Cerbos. The generated gRPC and protobuf code is available under the `github.com/cerbos/cerbos/api/genpb` package.

[source,sh]
----
go get github.com/cerbos/cerbos/api/genpb
----
You can also make use link:https://buf.build/cerbos/cerbos-api[Buf generated SDKs] to pull down the Cerbos gRPC API as a Go module:

[source,sh]
----
go get buf.build/gen/go/cerbos/cerbos-api/grpc/go@latest
----
