name: Free disk space
description: Remove unused files to free-up disk space
runs:
  using: composite
  steps:
    - shell: bash
      run: |-
        df -h
        sudo rm -rf \
          /opt/az \
          /opt/ghc \
          /opt/google \
          /opt/hostedtoolcache \
          /opt/microsoft \
          /usr/local/julia* \
          /usr/local/lib/android \
          /usr/local/share/powershell \
          /usr/share/dotnet
        sudo docker system prune --all --force || true
        sudo docker builder prune --all --force || true
        df -h
