name: Free disk space
description: Remove unused files to free-up disk space
runs:
  using: composite
  steps:
    - name: Install rmz
      uses: cerbos/actions/install-tools@3e513163c6e062721f84cd58125a5dfa5293e3b2 # main
      with:
        tools: rmz

    - name: Remove unused files
      shell: bash
      run: |
        df -h
        sudo env PATH="${PATH}" rmz -f \
          /opt/az \
          /opt/ghc \
          /opt/google \
          /opt/hostedtoolcache \
          /opt/microsoft \
          /usr/local/julia* \
          /usr/local/lib/android \
          /usr/local/share/powershell \
          /usr/share/dotnet
        sudo docker system prune --all --force || true
        sudo docker builder prune --all --force || true
        df -h
