style: github
template: CHANGELOG.tpl.adoc
info:
  title: CHANGELOG
  repository_url: https://github.com/cerbos/cerbos
options:
  commits:
    filters:
      Type:
        - feature
        - enhancement
        - bug
  commit_groups:
    group_by: Type
    title_maps:
      feature: Features
      enhancement: Enhancements
      bug: Bug fixes
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
