apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: PBFA97CFB590B2093
    url: $PROMETHEUS_URL
    version: 1