{
 "title": "Cerbos",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instances",
    "query": {
     "query": "label_values(go_threads{job=\"cerbos\"},instance)"
    }
   },
   {
    "name": "cache_kinds",
    "query": {
     "query": "label_values(cerbos_dev_cache_live_objects{job=\"cerbos\"},kind)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PDP Health and Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Policy Count",
   "type": "timeseries",
   "description": "The number of policies held by each PDP instance.",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cerbos_dev_index_entry_count{job=\"cerbos\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(cerbos_dev_index_entry_count{job=\"cerbos\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min by (instance) (cerbos_dev_index_entry_count{instance=~\"${instances}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PDP Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cerbos_dev_index_entry_count{job=\"cerbos\"}) ",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(cerbos_dev_hub_connected{job=\"cerbos\"} != 0) or vector(0)",
     "legendFormat": "Hub Connected"
    }
   ]
  },
  {
   "title": "Engine Evaluation Duration",
   "type": "heatmap",
   "description": "The distribution of the times required to evaluate the policies for incoming requests across all selected PDP instances.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(cerbos_dev_engine_check_latency_milliseconds_bucket{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RPC Call Duration",
   "type": "heatmap",
   "description": "The distribution of the times required to service all incoming requests across all selected PDP instances",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_call_duration_seconds_bucket{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Check Method Batch Sizes",
   "type": "heatmap",
   "description": "Requests to the Check method can include more than one request request to evaluate. This shows the distribution of the number of policy evaluations in each incoming request for all selected instances.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(cerbos_dev_engine_check_batch_size_bucket{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RPC Latency Percentiles",
   "type": "timeseries",
   "description": "The aggregate RPC latency for the selected instances. ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(rpc_server_call_duration_seconds_bucket{job=\"cerbos\",rpc_method=\"cerbos.svc.v1.CerbosService/CheckResources\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rpc_server_call_duration_seconds_bucket{job=\"cerbos\",rpc_method=\"cerbos.svc.v1.CerbosService/CheckResources\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(rpc_server_call_duration_seconds_bucket{job=\"cerbos\",rpc_method=\"cerbos.svc.v1.CerbosService/CheckResources\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(rpc_server_call_duration_seconds_bucket{job=\"cerbos\",rpc_method=\"cerbos.svc.v1.CerbosService/CheckResources\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) * 1000",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Check Latency Percentiles",
   "type": "timeseries",
   "description": "The Check evaluation latency percentiles for the selected instances.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(cerbos_dev_engine_check_latency_milliseconds_bucket{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cerbos_dev_engine_check_latency_milliseconds_bucket{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(cerbos_dev_engine_check_latency_milliseconds_bucket{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(cerbos_dev_engine_check_latency_milliseconds_bucket{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Compile Compilation Time  Percentiles",
   "type": "timeseries",
   "description": "Percentiles for the time take to compile policies for the selected instances.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(cerbos_dev_compiler_compile_duration_milliseconds_bucket{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cerbos_dev_compiler_compile_duration_milliseconds_bucket{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(cerbos_dev_compiler_compile_duration_milliseconds_bucket{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(cerbos_dev_compiler_compile_duration_milliseconds_bucket{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "This is the total request rate by RPC method and response status, for all selected instances.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_call_duration_seconds_count{job=\"cerbos\", instance=~\"${instances}\"}[$__rate_interval])) by (rpc_method, rpc_response_status_code)",
     "legendFormat": "{{rpc_method}}-{{rpc_response_status_code}}"
    }
   ]
  },
  {
   "title": "Request Rate by Instance",
   "type": "timeseries",
   "description": "The total number of requests handled by each of the selected instancecs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_call_duration_seconds_count{job=\"cerbos\", instance=~\"${instances}\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "The number of errors reported for each RPC by each selected instance. Not that some things reported as errors, such as CANCELLED, may not reflect an actual error within the PDP.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_call_duration_seconds_count{job=\"cerbos\", instance=~\"${instances}\", rpc_response_status_code != \"OK\"}[$__rate_interval])) by (rpc_method, rpc_response_status_code)",
     "legendFormat": "{{rpc_method}}-{{rpc_response_status_code}}"
    }
   ]
  },
  {
   "title": "Error Rate - by instance",
   "type": "timeseries",
   "description": "The total number of errors returned by each of the selected instances.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_call_duration_seconds_count{job=\"cerbos\", instance=~\"${instances}\", rpc_response_status_code != \"OK\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Cache (${cache_kinds})",
   "type": "timeseries",
   "description": "This shows the percentage of the internal cache used for each of the selected instances.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "repeat": "cache_kinds",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cerbos_dev_cache_live_objects{job=\"cerbos\",instance=~\"${instances}\",kind=\"${cache_kinds}\"} / cerbos_dev_cache_max_size{job=\"cerbos\",instance=~\"${instances}\",kind=\"${cache_kinds}\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cache Access (${cache_kinds})",
   "type": "timeseries",
   "description": "This shows the hit and miss rate  of the internal cache for each of the selected instances.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "repeat": "cache_kinds",
   "targets": [
    {
     "expr": "sum(rate(cerbos_dev_cache_access_count_total{job=\"cerbos\",instance=~\"${instances}\",kind=\"${cache_kinds}\"}[$__rate_interval])) by (kind, result, instance)",
     "legendFormat": "{{result}} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "This is the total resident memory in use by each instance.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (instance) (process_resident_memory_bytes{job=\"cerbos\",  instance=~\"${instances}\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "description": "This shows the rate of memory allocation operations performed by the Go runtime for each of the selected instances. More metrics related to the nature of the memory use of the PDP are exposed than are presented here.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memory_allocations_total{job=\"cerbos\",  instance=~\"${instances}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Pause Time",
   "type": "timeseries",
   "description": "The time spent in \"stop the world\" garbage collection for all selected instances.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (instance) (rate(go_gc_duration_seconds_sum{job=\"cerbos\",instance=~\"${instances}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "This is the amount of CPU being used by each selected instance. This is as reported by the instance itself. Alternative CPU measurements from your operating system may be more accurate.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (rate(process_cpu_seconds_total{job=\"cerbos\",  instance=~\"${instances}\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Go routines",
   "type": "timeseries",
   "description": "The number of active Go user space threads",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (go_goroutines{job=\"cerbos\", instance=~\"${instances}\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "timeseries",
   "description": "This is the number of active CPU threads allocated by the Go runtime",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (go_threads{job=\"cerbos\", instance=~\"${instances}\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "This is the network traffic level of each instance, as reported by the instance itself. Other systems may be able to provide a more accurate measurement.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by (instance) (rate(process_network_receive_bytes_total{job=\"cerbos\",  instance=~\"${instances}\"}[$__rate_interval]))",
     "legendFormat": "Recieved - {{ instance }}"
    },
    {
     "expr": "max by (instance) (rate(process_network_transmit_bytes_total{job=\"cerbos\",  instance=~\"${instances}\"}[$__rate_interval]))",
     "legendFormat": "Sent - {{ instance }}"
    },
    { "expr": "0", "legendFormat": "__zero" }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "The total number of file descriptors in use by each instance.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(process_open_fds{job=\"cerbos\", instance=~\"${instances}\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}