# Illustrates how to connect to Cerbos Cloud
# Prerequisites:
# - Sign-up to Cerbos Cloud and follow the instructions to create an API key
# - Create a Kubernetes secret named `cerbos-cloud-credentials`:
#      kubectl create secret generic cerbos-cloud-credentials \
#         --from-literal=CERBOS_CLOUD_CLIENT_ID=<YOUR_CLIENT_ID> \
#         --from-literal=CERBOS_CLOUD_CLIENT_SECRET=<YOUR_CLIENT_SECRET> \
#         --from-literal=CERBOS_CLOUD_SECRET_KEY=<YOUR_SECRET_KEY>

cerbos:
  config:
    # Configure the bundle storage driver
    storage:
      driver: "bundle"
      bundle:
        remote:
          bundleLabel: "YOUR_LABEL" # Alternatively, add `CERBOS_CLOUD_BUNDLE=<YOUR_LABEL>` to the secret you created above.

# Create environment variables from the secret.
envFrom:
  - secretRef:
      name: cerbos-cloud-credentials

