# Illustrates how to mount a volume containing policies to the Cerbos pod.

volumes:
  - name: cerbos-policies
    hostPath:
      path: /data/cerbos-policies

  - name: cerbos-scratch
    emptyDir: {}

volumeMounts:
  - name: cerbos-policies
    mountPath: /policies
    readOnly: true

  - name: cerbos-scratch
    mountPath: /scratch

cerbos:
  config:
    storage:
      driver: "disk"
      disk:
        directory: /policies
        watchForChanges: true
        scratchDir: /scratch
