---
site:
  title: Cerbos // Documentation
  url: https://docs.cerbos.dev
  robots: allow
  start_page: cerbos:ROOT:index.adoc
  keys:
    google_analytics: 'G-K7EZDLXSVN'
content:
  sources:
    - url: /github/workspace # Default location where GitHub actions mounts the source
      branches: ['HEAD']
      edit_url: 'https://github.com/cerbos/cerbos/tree/{refname}/{path}'
      start_path: docs
asciidoc:
  attributes:
    app-name: "cerbos"
    app-version: "0.0.2"
    experimental: true
    page-pagination: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  clean: true
  dir: ./build
  destinations:
    - provider: archive
      path: ./build/cerbos_docs.zip
