include::ROOT:partial$attributes.adoc[]

= Deploy Cerbos to Cloud platforms

include::ROOT:partial$version-check.adoc[]

== Fly.io

You can deploy Cerbos on Fly.io as a link:https://fly.io/docs/apps[Fly Launch] app. The following `fly.toml` file shows
how to deploy Cerbos with healthchecks and metrics:
[source,toml,linenums,subs="attributes+"]
----
app = '<APPLICATION_NAME>' <1>
primary_region = '<REGION>' <2>

[build]
  image = 'ghcr.io/cerbos/cerbos:{app-version}'

[[mounts]]
  source = 'policies'
  destination = '/policies'
  initial_size = '1GB'

[[services]]
  protocol = ''
  internal_port = 3592

[[services.ports]]
    port = 3592
    handlers = ['tls', 'http']

[[services.http_checks]]
    interval = '5s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/_cerbos/health'
    protocol = 'http'

[[services]]
  protocol = ''
  internal_port = 3593

[[services.ports]]
    port = 3593
    handlers = ['tls']

    [services.ports.tls_options]
      alpn = ['h2']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[metrics]
  port = 3592
  path = "/_cerbos/metrics"
----
<1> The name of the link:https://fly.io/docs/apps[Fly App]
<2> Pick a Fly.io link:https://fly.io/docs/reference/regions/#fly-io-regions[region]

The example above launches a Cerbos instance with the
xref:configuration:index.adoc#minimal-configuration[minimal configuration] using an empty
link:https://fly.io/docs/reference/volumes/[Fly volume] mounted as the policy directory. For production use cases, we
recommend using either the xref:configuration:storage.adoc#blob-driver[blob driver] with
link:https://fly.io/docs/reference/tigris/#create-and-manage-a-tigris-storage-bucket[Tigris],
xref:configuration:storage.adoc#git-driver[git driver] with a Git provider,
xref:configuration:storage.adoc#sqlite3[sqlite3 driver] locally or with
link:https://fly.io/docs/litefs/#litefs-cloud[LiteFS],
xref:configuration:storage.adoc#postgres[postgres driver] with
link:https://fly.io/docs/postgres/[Fly Postgres] or link:https://www.cerbos.dev/product-cerbos-hub[Cerbos Hub bundles]
as the policy storage backend. Cerbos can be xref:configuration:index.adoc[configured entirely from the command line]
using the `--set` flags. On the Fly.io platform, they can be set by overriding the `cmd` setting in the
link:https://fly.io/docs/reference/configuration/#the-experimental-section[experimental section] of the `fly.toml` file.

=== Using Tigris as a policy repository

Cerbos `blob` driver can be used with any S3-compatible blob storage backend such as
link:https://fly.io/docs/reference/tigris[Tigris]. To set the credentials for accessing the bucket, use the
`flyctl secrets` command.
[source,bash]
----
flyctl secrets set AWS_ACCESS_KEY_ID=tid_XXXXXX <1>
flyctl secrets set AWS_SECRET_ACCESS_KEY=tsec_XXXXXX <2>
----
<1> Tigris key ID
<2> Tigris secret access key


[source,toml,linenums,subs="attributes+"]
----
app = '<APPLICATION_NAME>' <1>
primary_region = '<REGION>' <2>

[build]
  image = 'ghcr.io/cerbos/cerbos:{app-version}'

[experimental]
  cmd = [
    'server',
    '--set', 'storage.driver=blob',
    '--set', 'storage.blob.bucket=s3://<BUCKET_NAME>?endpoint=fly.storage.tigris.dev&region=auto', <3>
    '--set', 'storage.blob.downloadTimeout=30s',
    '--set', 'storage.blob.prefix=policies',
    '--set', 'storage.blob.updatePollInterval=15s',
    '--set', 'storage.blob.workDir=/policies'
  ]

[[mounts]]
  source = 'policies'
  destination = '/policies'
  initial_size = '1GB'

[[services]]
  protocol = ''
  internal_port = 3592
  auto_stop_machines = true

[[services.ports]]
    port = 3592
    handlers = ['tls', 'http']

[[services.http_checks]]
    interval = '5s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/_cerbos/health'
    protocol = 'http'

[[services]]
  protocol = ''
  internal_port = 3593
  auto_stop_machines = true

[[services.ports]]
    port = 3593
    handlers = ['tls']

    [services.ports.tls_options]
      alpn = ['h2']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[metrics]
  port = 3592
  path = "/_cerbos/metrics"
----
<1> The name of the link:https://fly.io/docs/apps[Fly App]
<2> Pick a Fly.io link:https://fly.io/docs/reference/regions/#fly-io-regions[region]
<3> Bucket name

=== Using LiteFS as a policy repository

Fly.io's distributed SQLite storage layer link:https://fly.io/docs/litefs[LiteFS] can be used for policy storage using
Cerbos' `sqlite3` driver.

.Create a LiteFS configuration file (`litefs.yml`)
[source,yaml,linenums]
----
data:
  dir: "/var/lib/litefs"

exec:
  - cmd: "/cerbos server --set=storage.driver=sqlite3 --set=storage.sqlite3.dsn=file:/litefs/db --set=server.adminAPI.enabled=true --set=server.adminAPI.adminCredentials.username=$CERBOS_ADMIN_USER --set=server.adminAPI.adminCredentials.passwordHash=$CERBOS_ADMIN_PASSWORD" <1>

exit-on-error: false

fuse:
  dir: "/litefs"

lease:
  advertise-url: "http://${FLY_ALLOC_ID}.vm.${FLY_APP_NAME}.internal:20202"
  candidate: ${FLY_REGION == PRIMARY_REGION}
  consul:
    url: "${FLY_CONSUL_URL}"
    key: "${FLY_APP_NAME}/primary"
  promote: true
  type: "consul"
----
<1> LiteFS requires us to set the command in the LiteFS configuration instead of using the Dockerfile. When LiteFS is
run it runs the command specified and waits until it exits.

NOTE: Refer to link:https://fly.io/docs/litefs/getting-started-docker/#configuring-litefs[Configuring LiteFS] documentation for other available configuration parameters.

.Create secrets for Admin API credentials
[source,bash]
----
flyctl secrets set CERBOS_ADMIN_USER=cerbos <1>
flyctl secrets set CERBOS_ADMIN_PASSWORD=$(echo "cerbosAdmin" | htpasswd -niBC 10 cerbos | cut -d ':' -f 2 | base64 -w0) <2>
----
<1> Specify username for Admin API
<2> Specify password for Admin API

.Create a Dockerfile
[source,Dockerfile,subs="attributes+"]
----
FROM flyio/litefs:0.5 AS litefs

FROM ghcr.io/cerbos/cerbos:{app-version} AS cerbos

FROM alpine:3.16 AS base
RUN apk add fuse3 sqlite
ADD litefs.yml /etc/litefs.yml
COPY --from=cerbos /cerbos /cerbos
COPY --from=litefs /usr/local/bin/litefs /usr/local/bin/litefs

ENTRYPOINT ["litefs"]
CMD ["mount"]
----

.Create a `fly.toml` to launch Cerbos
[source,toml,linenums,subs="attributes+"]
----
app = '<APPLICATION_NAME>' <1>
primary_region = '<REGION>' <2>

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs" <3>

[[services]]
  protocol = ''
  internal_port = 3592

[[services.ports]]
    port = 3592
    handlers = ['tls', 'http']

[[services.http_checks]]
    interval = '5s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/_cerbos/health'
    protocol = 'http'

[[services]]
  protocol = ''
  internal_port = 3593

[[services.ports]]
    port = 3593
    handlers = ['tls']

    [services.ports.tls_options]
      alpn = ['h2']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[metrics]
  port = 3592
  path = "/_cerbos/metrics"
----
<1> The name of the link:https://fly.io/docs/apps[Fly App]
<2> Pick a link:https://fly.io/docs/reference/regions/#fly-io-regions[region]
<3> Destination must be equal to the one specified in the `litefs.yaml`

.Attach to Consul to manage LiteFS leases.
[source,bash]
----
flyctl consul attach
----

NOTE: See link:https://fly.io/docs/litefs/getting-started-fly/#lease-configuration[lease configuration] for more
information about Consul leases on Fly.io.

You can interact with the Cerbos xref:api:admin_api.adoc[Admin API] using one of the Cerbos SDKs or the xref:cli:cerbosctl.adoc[`cerbosctl`] utility to manage the policies stored on LiteFS.

.List policies with cerbosctl
[source,bash,linenums]
----
cerbosctl \
  --server=https://<APPLICATION_NAME>.fly.dev \ <1>
  --username="cerbos" \
  --password="cerbosAdmin" \
  get derived_roles
----
<1> The name of the link:https://fly.io/docs/apps[Fly App]

.Put a policy or a directory consisting of multiple policies with cerbosctl
[source,bash,linenums]
----
cerbosctl \
  --server=https://<APPLICATION_NAME>.fly.dev \ <1>
  --username="cerbos" \
  --password="cerbosAdmin" \
  put policies -R \
  policy_dir
----
<1> The name of the link:https://fly.io/docs/apps[Fly App]
