---
name: AWS
on:
  workflow_dispatch:
jobs:
  publishContainers:
    name: Publish Dev Containers
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          lfs: true
          persist-credentials: false

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # v2.1.5
        with:
          registries: ${{ vars.AWS_CONTAINER_REGISTRY_ID }}

      - name: Install Go and cache dependencies
        uses: ./.github/actions/setup-go
        with:
          cross_compiling: true
          write_build_cache: true

      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Install goreleaser
        uses: cerbos/actions/install-tools@f73c5fd3cd8b66cad9d757a8686cc30d0f209f84 # main
        with:
          tools: goreleaser

      - name: GoReleaser
        run: goreleaser release --config=.goreleaser.yml --clean --snapshot --skip=publish
        env:
          AWS_CONTAINER_REPO: ${{ vars.AWS_CONTAINER_REPO }}
          AWS_PRODUCT_CODE: ${{ vars.AWS_PRODUCT_CODE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEMETRY_WRITE_KEY: ${{ secrets.TELEMETRY_WRITE_KEY }}
          TELEMETRY_URL: ${{ secrets.TELEMETRY_URL }}

      - name: Push Cerbos dev images to ECR
        run: |
          docker push "${VARS_AWS_CONTAINER_REPO}:dev-amd64"
          docker push "${VARS_AWS_CONTAINER_REPO}:dev-arm64"
          docker manifest create "${VARS_AWS_CONTAINER_REPO}:dev" "${VARS_AWS_CONTAINER_REPO}:dev-arm64" "${VARS_AWS_CONTAINER_REPO}:dev-amd64"
          docker manifest push "${VARS_AWS_CONTAINER_REPO}:dev"
        env:
          VARS_AWS_CONTAINER_REPO: ${{ vars.AWS_CONTAINER_REPO }}
