---
name: AWS
on:
  workflow_dispatch:
jobs:
  publishContainers:
    name: Publish Dev Containers
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          lfs: true
          persist-credentials: false

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registries: ${{ vars.AWS_CONTAINER_REGISTRY_ID }}

      - name: Install Go and cache dependencies
        uses: ./.github/actions/setup-go
        with:
          cross_compiling: true
          write_build_cache: true

      - name: Install cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: latest
          args: release --config=.goreleaser.yml --clean --snapshot --skip=publish
        env:
          AWS_CONTAINER_REPO: ${{ vars.AWS_CONTAINER_REPO }}
          AWS_PRODUCT_CODE: ${{ vars.AWS_PRODUCT_CODE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEMETRY_WRITE_KEY: ${{ secrets.TELEMETRY_WRITE_KEY }}
          TELEMETRY_URL: ${{ secrets.TELEMETRY_URL }}

      - name: Push Cerbos dev images to ECR
        run: |
          docker push ${VARS_AWS_CONTAINER_REPO}:dev-amd64
          docker push ${VARS_AWS_CONTAINER_REPO}:dev-arm64
          docker manifest create ${VARS_AWS_CONTAINER_REPO}:dev ${VARS_AWS_CONTAINER_REPO}:dev-arm64 ${VARS_AWS_CONTAINER_REPO}:dev-amd64
          docker manifest push ${VARS_AWS_CONTAINER_REPO}:dev
        env:
          VARS_AWS_CONTAINER_REPO: ${{ vars.AWS_CONTAINER_REPO }}
