name: Cache dependencies

on:
  push:
    branches:
      - main
  workflow_call:
permissions: {}

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      pull-requests: read
    outputs:
      deps: ${{ steps.filter.outputs.deps }}
    steps:
      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        with:
          filters: |
            deps:
              - .github/workflows/cache.yaml
              - "**/go.mod"

  cache:
    name: Cache dependencies
    needs: changes
    if: ${{ needs.changes.outputs.deps == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions: {}
    steps:
      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Install Go and cache dependencies
        id: setup
        uses: ./.github/actions/setup-go
        with:
          write_deps_cache: true
          write_build_cache: true

      - name: Install just
        uses: cerbos/actions/install-tools@77b46c5f4ff1aebe72b5a8017d561a0f5a9b6845 # main
        with:
          tools: just

      - name: Warm cache
        if: ${{ steps.setup.outputs.cache_hit != 'true' }}
        run: just warm-cache
