name: Cache dependencies

on:
  push:
    branches:
      - main
  workflow_call:
permissions: {}

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      pull-requests: read
    outputs:
      deps: ${{ steps.filter.outputs.deps }}
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            deps:
              - .github/workflows/cache.yaml
              - "**/go.mod"

  cache:
    name: Cache dependencies
    needs: changes
    if: ${{ needs.changes.outputs.deps == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions: {}
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Install Go and cache dependencies
        id: setup
        uses: ./.github/actions/setup-go
        with:
          write_deps_cache: true
          write_build_cache: true

      - name: Install just
        uses: cerbos/actions/install-tools@aff2ae494c8b0f0a9e9faee6d5974221a21617da # main
        with:
          tools: just

      - name: Warm cache
        if: ${{ steps.setup.outputs.cache_hit != 'true' }}
        run: just warm-cache
