name: Dependabot
on:
  pull_request
permissions:
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Generate notice
        run: "make deps generate-notice"

      - name: Commit NOTICE
        uses: EndBug/add-and-commit@v9
        with:
          message: Generate NOTICE
          committer_name: Cerbos Actions
          committer_email: info@cerbos.dev
          signoff: true
          push: origin
