name: Dependabot
on:
  pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    #if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Generate notice
        run: "make deps generate-notice"

      - name: Commit NOTICE
        run: |
          git config --global user.name 'Cerbos Actions'
          git config --global user.email 'info@cerbos.dev'
          git commit -am "Generate NOTICE"
          git push

