---
name: E2E Tests
on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package"
        required: false
        type: string
        default: ""
  schedule:
    - cron: 0 1 * * 1-5
permissions: {}
jobs:
  runE2ETests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Install Go and restore cached dependencies
        uses: ./.github/actions/setup-go

      - name: Install tools
        uses: cerbos/actions/install-tools@6e173289a5f7dbcc0a62e6cb761e18f22f0b2070 # main
        with:
          tools: |-
            helm
            helmfile
            kind
            kubectl
            stern
            telepresence

      - name: Install Helm Secrets
        shell: bash
        run: helm plugin install https://github.com/jkroepke/helm-secrets --version v4.7.6

      - name: Configure Telepresence
        run: |
          mkdir -p ~/.config/telepresence
          cat >~/.config/telepresence/config.yml <<EOF
          timeouts:
            helm: 60s
            trafficManagerAPI: 30s
          EOF

      - name: Initialize Helmfile
        run: helmfile init --force

      - name: Run E2E Tests
        run: e2e/run.sh
        env:
          E2E_NO_CLEANUP: "true"
          E2E_PACKAGE: ${{ inputs.package }}

      - name: Notify Slack on failure
        if: failure()
        uses: cerbos/actions/notify-slack@6e173289a5f7dbcc0a62e6cb761e18f22f0b2070 # main
        with:
          webhook-url: ${{ secrets.SLACK_CI_NOTIFICATIONS_WEBHOOK_URL }}
