---
name: CI
on:
  pull_request:
    branches:
      - main
      - "v*"
      - "feat/*"
permissions: {}
jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read
    outputs:
      actions: ${{ steps.filter.outputs.actions }}
      code: ${{ steps.filter.outputs.code }}
      docs: ${{ steps.filter.outputs.docs }}
      npm: ${{ steps.filter.outputs.npm }}
      protos: ${{ steps.filter.outputs.protos }}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            actions:
              - '.github/**'
            code:
              - '!(.node-version|{docs,npm}/**)'
            docs:
              - .github/workflows/pr-test.yaml
              - 'docs/**'
            npm:
              - .github/workflows/pr-test.yaml
              - 'npm/**'
              - .node-version
            protos:
              - .github/workflows/pr-test.yaml
              - '**/*.proto'

  cache:
    uses: ./.github/workflows/cache.yaml
    permissions:
      pull-requests: read

  generate:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    name: Generate
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions: {}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Install Go and restore cached dependencies
        uses: ./.github/actions/setup-go

      - name: Install just
        uses: ./.github/actions/setup-just

      - name: Generate
        run: just generate

      - name: Check repo status
        run: |-
          REPO_STATUS="$(git status --porcelain)"
          if [[ ! -z $REPO_STATUS ]]; then
            echo "::error::Uncommitted changes detected"
            echo "$REPO_STATUS"
            exit 1
          fi

  download-test-times:
    name: Download test times
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Download previous test times
        continue-on-error: true
        uses: dawidd6/action-download-artifact@fe9d59ce33ce92db8a6ac90b2c8be6b6d90417c8 # v15
        with:
          workflow: pr-test.yaml
          name: test-times
          search_artifacts: true

      - name: Upload previous test times
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: previous-test-times
          path: test-times.json

  test:
    needs:
      - changes
      - download-test-times
    if: ${{ needs.changes.outputs.code == 'true' }}
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions: {}
    strategy:
      fail-fast: false
      matrix:
        split: [0, 1, 2, 3, 4, 5]
    outputs:
      job-total: ${{ strategy.job-total }}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
          persist-credentials: false

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Install Go and restore cached dependencies
        uses: ./.github/actions/setup-go

      - name: Install just
        uses: ./.github/actions/setup-just

      - name: Download previous test times
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: previous-test-times

      - name: Test
        run: just test-all ${STRATEGY_JOB_INDEX} ${STRATEGY_JOB_TOTAL}
        env:
          GOEXPERIMENT: loopvar # https://github.com/golang/go/wiki/LoopvarExperiment
          CERBOS_LOG_LEVEL: "debug"
          CERBOS_TEST_LOG_LEVEL: "debug"
          CERBOS_DEBUG_DB: "true"
          CERBOS_DEBUG_ENGINE: "true"
          CERBOS_DEBUG_KAFKA: "true"
          CERBOS_HUB_API_ENDPOINT: "${{ secrets.CERBOS_HUB_API_ENDPOINT }}"
          CERBOS_HUB_CLIENT_ID: "${{ secrets.CERBOS_HUB_CLIENT_ID }}"
          CERBOS_HUB_CLIENT_SECRET: "${{ secrets.CERBOS_HUB_CLIENT_SECRET }}"
          CERBOS_HUB_STORE_ID: "${{ secrets.CERBOS_HUB_STORE_ID }}"
          STRATEGY_JOB_INDEX: ${{ strategy.job-index }}
          STRATEGY_JOB_TOTAL: ${{ strategy.job-total }}

      - name: Upload JUnit reports
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: junit-reports-${{ strategy.job-index }}
          path: junit.*.xml

      - name: Upload unit coverage to Coveralls
        uses: shogo82148/actions-goveralls@25f5320d970fb565100cf1993ada29be1bb196a1 # v1.10.0
        continue-on-error: true
        with:
          path-to-profile: unit.cover
          flag-name: unit-${{ strategy.job-index }}
          parallel: true

      - name: Upload integration coverage to Coveralls
        uses: shogo82148/actions-goveralls@25f5320d970fb565100cf1993ada29be1bb196a1 # v1.10.0
        continue-on-error: true
        with:
          path-to-profile: integration.cover
          flag-name: integration-${{ strategy.job-index }}
          parallel: true

  upload-test-times:
    needs: test
    if: ${{ always() && needs.test.result != 'skipped' }}
    name: Upload test times
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Check test results
        run: test "${NEEDS_TEST_RESULT}" = "success"
        env:
          NEEDS_TEST_RESULT: ${{ needs.test.result }}

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: 1.26.x
          cache: false
          check-latest: true

      - name: Install just
        uses: ./.github/actions/setup-just

      - name: Download JUnit reports
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0

      - name: Combine JUnit reports
        run: |-
          mv junit-reports-*/junit.*.xml .
          just test-times ${NEEDS_TEST_OUTPUTS_JOB_TOTAL}
        env:
          NEEDS_TEST_OUTPUTS_JOB_TOTAL: ${{ needs.test.outputs.job-total }}

      - name: Upload new test times
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: test-times
          path: test-times.json

      - name: Complete coveralls report
        uses: shogo82148/actions-goveralls@25f5320d970fb565100cf1993ada29be1bb196a1 # v1.10.0
        continue-on-error: true
        with:
          parallel-finished: true

  docs:
    needs: changes
    if: ${{ needs.changes.outputs.docs == 'true' }}
    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          lfs: true
          persist-credentials: false

      - name: Generate docs
        uses: ./.github/actions/antora-docs
        id: docs

  golangci:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: 1.26.x
          check-latest: true

      - name: Install just
        uses: ./.github/actions/setup-just

      - name: Compile
        run: just compile

      - name: modernize
        run: just lint-modernize

      - name: golangci-lint
        uses: ./.github/actions/golangci-lint

  buf:
    needs: changes
    if: ${{ needs.changes.outputs.protos == 'true' }}
    name: Proto check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: write
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Lint protos
        uses: bufbuild/buf-action@8f4a1456a0ab6a1eb80ba68e53832e6fcfacc16c # v1.3.0
        with:
          breaking: false
          format: true
          lint: true

      - name: Find latest release
        id: latest-release
        run: gh release view --json tagName --jq '"tag=\(.tagName)"' >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Set latest release commit ID
        id: latest_release_commit_id
        run: |
          echo "LATEST_RELEASE_COMMIT_ID=$(git rev-list -n 1 tags/${STEPS_LATEST_RELEASE_OUTPUTS_TAG})" >> "$GITHUB_OUTPUT"
        env:
          STEPS_LATEST_RELEASE_OUTPUTS_TAG: ${{ steps.latest-release.outputs.tag }}

      - name: Check backwards compatibility
        uses: cerbos/buf-breaking-action@b637955df51832cca5dd244fb3ac9ab35781cdb5 # since
        with:
          against: https://github.com/cerbos/cerbos.git#ref=${{ steps.latest_release_commit_id.outputs.LATEST_RELEASE_COMMIT_ID }}
          since: https://github.com/cerbos/cerbos.git#ref=main

  test-helm:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    name: Helm test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.26.x"

      - name: Test Helm chart
        run: ./deploy/charts/validate.sh

  build-npm:
    needs: changes
    if: ${{ needs.changes.outputs.npm == 'true' }}
    name: Build npm packages
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions: {}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Install Go and cache dependencies
        uses: ./.github/actions/setup-go
        with:
          cross_compiling: true

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@17ae1740179002c89186b61233e0f892c3118b11 # v0.23.0

      - name: Build binaries
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          version: latest
          args: build --config=.goreleaser.yml --clean --snapshot
        env:
          AWS_CONTAINER_REPO: ${{ vars.AWS_CONTAINER_REPO }}
          AWS_PRODUCT_CODE: ${{ vars.AWS_PRODUCT_CODE }}
          TELEMETRY_WRITE_KEY: ${{ secrets.TELEMETRY_WRITE_KEY }}
          TELEMETRY_URL: ${{ secrets.TELEMETRY_URL }}

      - name: Collect npm packages
        run: tar --create --verbose --file npm.tar npm

      - name: Upload npm packages
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: npm-packages
          path: npm.tar

  test-npm:
    needs: build-npm
    name: Test npm packages
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 10
    permissions: {}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Check out .node-version file
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .node-version
            hack/scripts/install-corepack.sh
          sparse-checkout-cone-mode: false
          persist-credentials: false

      - name: Download npm packages
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: npm-packages

      - name: Extract npm packages
        run: tar --extract --verbose --file npm.tar

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: npm
          cache-dependency-path: npm/test/registry/package-lock.json
          node-version-file: .node-version

      # https://github.com/actions/runner-images/issues/9626
      - name: Don't force curl to use IPv4
        run: rm -f ~/.curlrc

      - name: Install corepack
        run: hack/scripts/install-corepack.sh

      - name: Test npm packages
        working-directory: npm
        run: corepack npm test

  test-npm-results:
    name: Check results of npm package tests
    runs-on: ubuntu-latest
    permissions: {}
    if: always() && needs.test-npm.result != 'skipped'
    needs:
      - test-npm
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Check test results
        run: test "${NEEDS_TEST_NPM_RESULT}" = "success"
        env:
          NEEDS_TEST_NPM_RESULT: ${{ needs.test-npm.result }}

  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.actions == 'true' }}
    permissions:
      security-events: write
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
