---
name: Release Helm chart
on:
  workflow_dispatch:
  push:
    tags:
      - helm/v*

jobs:
  publishHelm:
    name: Publish Helm chart
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    env:
      CHARTS_DIR: deploy/out/helm-charts
      OCI_REGISTRY: ghcr.io/cerbos/helm-charts
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Helm
        uses: cerbos/actions/install-tools@148106e618c65e91a0026179ccf0cff043e6b962 # main
        with:
          tools: helm

      - name: GCloud Auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY}}

      - name: Install Cloud SDK
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1

      - name: Package Helm chart
        run: |-
          mkdir -p ${{ env.CHARTS_DIR }}/cerbos
          helm package -d ${{ env.CHARTS_DIR }}/cerbos deploy/charts/cerbos

      - name: Publish to download site
        run: |-
          gsutil cp "gs://${{ secrets.DOWNLOAD_GCS_BUCKET }}/helm-charts/index.yaml" "${{ env.CHARTS_DIR }}/index.yaml"
          helm repo index --url=https://download.cerbos.dev/helm-charts --merge=${{ env.CHARTS_DIR }}/index.yaml ${{ env.CHARTS_DIR }}
          gsutil rsync -r ${{ env.CHARTS_DIR }}/ "gs://${{ secrets.DOWNLOAD_GCS_BUCKET }}/helm-charts/"
